Nursing home student: model.Person Class Reference
model.Person Class Reference abstract
Public Member Functions
Person (String firstName, String surname)
constructs a person from the given params.
String getFirstName ()
void setFirstName (String firstName)
String getSurname ()
void setSurname (String surname)
Private Attributes
String firstName
String surname
Detailed Description
Constructor & Destructor Documentation
Person()
model.Person.Person (String firstName, String surname)
constructs a person from the given params.
Parameters
firstName
surname
{
        this.firstName = firstName;
        this.surname = surname;
    }
References model.Person.firstName, and model.Person.surname.
Member Function Documentation
getFirstName()
String model.Person.getFirstName ()
Returns
firstname
{
        return firstName;
    }
References model.Person.firstName.
Referenced by datastorage.CaregiverDAO.getCreateStatementString(), datastorage.PatientDAO.getCreateStatementString(), datastorage.CaregiverDAO.getUpdateStatementString(), datastorage.PatientDAO.getUpdateStatementString(), controller.TreatmentController.showData(), controller.NewTreatmentController.showPatientData(), model.Caregiver.toString(), and model.Patient.toString().
getSurname()
String model.Person.getSurname ()
Returns
surname
{
        return surname;
    }
References model.Person.surname.
Referenced by datastorage.CaregiverDAO.getCreateStatementString(), datastorage.PatientDAO.getCreateStatementString(), datastorage.CaregiverDAO.getUpdateStatementString(), datastorage.PatientDAO.getUpdateStatementString(), controller.TreatmentController.showData(), controller.NewTreatmentController.showPatientData(), model.Caregiver.toString(), and model.Patient.toString().
setFirstName()
void model.Person.setFirstName (String firstName)
Parameters
firstName
{
        this.firstName = firstName;
    }
References model.Person.firstName.
setSurname()
void model.Person.setSurname (String surname)
Parameters
surname
{
        this.surname = surname;
    }
References model.Person.surname.
Member Data Documentation
firstName
String model.Person.firstName private
Referenced by model.Caregiver.Caregiver(), model.Person.getFirstName(), model.Patient.Patient(), model.Person.Person(), and model.Person.setFirstName().
surname
String model.Person.surname private
Referenced by model.Caregiver.Caregiver(), model.Person.getSurname(), model.Patient.Patient(), model.Person.Person(), and model.Person.setSurname().
The documentation for this class was generated from the following file:
src/main/java/model/Person.java