Nursing home student: model.Caregiver Class Reference
model.Caregiver Class Reference
Caregiver nurse residents in a NURSING home.
Public Member Functions
Caregiver (String firstName, String surname, String telephone, boolean shown)
constructs a caregiver from the given params.
Caregiver (long id, String firstName, String surname, String telephone, boolean shown)
constructs a caregiver from the given params.
long getId ()
String getTelephone ()
void setTelephone (String telephone)
boolean isShown ()
void setShown (boolean shown)
boolean add (Treatment m)
adds a treatment to the treatment-list, if it does not already contain it.
String toString ()
Public Member Functions inherited from model.Person
Person (String firstName, String surname)
constructs a person from the given params.
String getFirstName ()
void setFirstName (String firstName)
String getSurname ()
void setSurname (String surname)
Private Attributes
long id
String telephone
boolean shown
List< Treatment > allTreatments = new ArrayList<Treatment>()
Detailed Description
Caregiver nurse residents in a NURSING home.
Constructor & Destructor Documentation
Caregiver() [1/2]
model.Caregiver.Caregiver (String firstName, String surname, String telephone, boolean shown)
constructs a caregiver from the given params.
Parameters
firstName
surname
telephone
shown
{
        super(firstName, surname);
        this.telephone = telephone;
        this.shown = shown;
    }
References model.Person.firstName, model.Caregiver.shown, model.Person.surname, and model.Caregiver.telephone.
Caregiver() [2/2]
model.Caregiver.Caregiver (long id, String firstName, String surname, String telephone, boolean shown)
constructs a caregiver from the given params.
Parameters
id
firstName
surname
telephone
shown
{
        super(firstName, surname);
        this.id = id;
        this.telephone = telephone;
        this.shown = shown;
    }
References model.Person.firstName, model.Caregiver.id, model.Caregiver.shown, model.Person.surname, and model.Caregiver.telephone.
Member Function Documentation
add()
boolean model.Caregiver.add (Treatment m)
adds a treatment to the treatment-list, if it does not already contain it.
Parameters
m Treatment
Returns
true if the treatment was not already part of the list. otherwise false
{
        if (!this.allTreatments.contains(m)) {
            this.allTreatments.add(m);
            return true;
        }
        return false;
    }
getId()
long model.Caregiver.getId ()
Returns
caregiver id
{
        return id;
    }
References model.Caregiver.id.
Referenced by datastorage.CaregiverDAO.getUpdateStatementString(), controller.NewTreatmentController.handleAdd(), and controller.AllCaregiverController.handleDeleteRow().
getTelephone()
String model.Caregiver.getTelephone ()
Returns
telephone number as a string
{
        return telephone;
    }
References model.Caregiver.telephone.
Referenced by datastorage.CaregiverDAO.getCreateStatementString(), and datastorage.CaregiverDAO.getUpdateStatementString().
isShown()
boolean model.Caregiver.isShown ()
Returns
shown status as boolean
{
        return shown;
    }
References model.Caregiver.shown.
Referenced by datastorage.CaregiverDAO.getUpdateStatementString().
setShown()
void model.Caregiver.setShown (boolean shown)
Parameters
shown as boolean
{
        this.shown = shown;
    }
References model.Caregiver.shown.
Referenced by controller.AllCaregiverController.handleBlockRow().
setTelephone()
void model.Caregiver.setTelephone (String telephone)
Parameters
telephone as string
{
        this.telephone = telephone;
    }
References model.Caregiver.telephone.
toString()
String model.Caregiver.toString ()
Returns
string-representation of the caregiver
{
        return "Caregiver" + "\nMNID: " + this.id +
                "\nFirstname: " + this.getFirstName() +
                "\nSurname: " + this.getSurname() +
                "\nBirthday: " + this.telephone +
                "\n";
    }
References model.Person.getFirstName(), and model.Person.getSurname().
Member Data Documentation
allTreatments
List<Treatment> model.Caregiver.allTreatments = new ArrayList<Treatment>() private
id
long model.Caregiver.id private
Referenced by model.Caregiver.Caregiver(), and model.Caregiver.getId().
shown
boolean model.Caregiver.shown private
Referenced by model.Caregiver.Caregiver(), model.Caregiver.isShown(), and model.Caregiver.setShown().
telephone
String model.Caregiver.telephone private
Referenced by model.Caregiver.Caregiver(), model.Caregiver.getTelephone(), and model.Caregiver.setTelephone().
The documentation for this class was generated from the following file:
src/main/java/model/Caregiver.java