Nursing home student: account.UserManager Class Reference
account.UserManager Class Reference
Public Member Functions
UserManager (Connection connection)
boolean isLoggedIn ()
void Login (String username, String password)
Static Public Member Functions
static UserManager getInstance ()
Package Attributes
Connection connection
Private Attributes
boolean LoggedIn
int LoggedInUserID
Static Private Attributes
static UserManager instance
Detailed Description
Constructor & Destructor Documentation
UserManager()
account.UserManager.UserManager (Connection connection)
{
        this.connection = connection;
    }
References account.UserManager.connection.
Referenced by account.UserManager.getInstance().
Member Function Documentation
getInstance()
static UserManager account.UserManager.getInstance () static
{
        if(instance == null) {
            instance = new UserManager(ConnectionBuilder.getConnection());
        }
        return instance;
    }
References datastorage.ConnectionBuilder.getConnection(), account.UserManager.instance, and account.UserManager.UserManager().
Referenced by controller.LoginWindowController.handleLogin().
isLoggedIn()
boolean account.UserManager.isLoggedIn ()
{
        return LoggedIn;
    }
References account.UserManager.LoggedIn.
Referenced by controller.LoginWindowController.handleLogin().
Login()
void account.UserManager.Login (String username, String password)
{
        String password_hashed =  Sha256.getSecurePassword(password, username);
        try {
            Statement statement = connection.createStatement();
            ResultSet result = statement.executeQuery(String.format("SELECT * FROM logins WHERE USERNAME = \'%s\'",  username));
            String s = "";
            while(result.next()) {
                s = result.getString("PASSWORD");
                LoggedInUserID = result.getInt("ID");
            }
            if(s.equals(password_hashed)) {
                LoggedIn = true;
            }
        } catch (SQLException e) {
            Logger.getLogger("loger").entering(getClass().getName(), e.getMessage());
            System.err.println("GO FUCK YOURSELF " + e.getMessage());
        }
    }
References account.UserManager.connection, utils.Sha256.getSecurePassword(), account.UserManager.LoggedIn, and account.UserManager.LoggedInUserID.
Referenced by controller.LoginWindowController.handleLogin().
Member Data Documentation
connection
Connection account.UserManager.connection package
Referenced by account.UserManager.Login(), and account.UserManager.UserManager().
instance
UserManager account.UserManager.instance static private
Referenced by account.UserManager.getInstance().
LoggedIn
boolean account.UserManager.LoggedIn private
Referenced by account.UserManager.isLoggedIn(), and account.UserManager.Login().
LoggedInUserID
int account.UserManager.LoggedInUserID private
Referenced by account.UserManager.Login().
The documentation for this class was generated from the following file:
src/main/java/account/UserManager.java