Nursing home student: datastorage.DAOFactory Class Reference
datastorage.DAOFactory Class Reference
creates the DAOs for the Patient, Treatment and Caregiver
Public Member Functions
TreatmentDAO createTreatmentDAO ()
creates a new instance of the TreatmentDAO
PatientDAO createPatientDAO ()
creates a new instance of the PatientDAO
CaregiverDAO createCaregiverDAO ()
creates a new instance of the CaregiverDAO
Static Public Member Functions
static DAOFactory getDAOFactory ()
Singleton which instantiates a new Object of this class if none already exists.
Private Member Functions
DAOFactory ()
privater constructor to prevent free initializing of a new object
Static Private Attributes
static DAOFactory instance
Detailed Description
creates the DAOs for the Patient, Treatment and Caregiver
Constructor & Destructor Documentation
DAOFactory()
datastorage.DAOFactory.DAOFactory () private
privater constructor to prevent free initializing of a new object
{
    }
Referenced by datastorage.DAOFactory.getDAOFactory().
Member Function Documentation
createCaregiverDAO()
CaregiverDAO datastorage.DAOFactory.createCaregiverDAO ()
creates a new instance of the CaregiverDAO
Returns
instance of the CaregiverDAO
{
        return new CaregiverDAO(ConnectionBuilder.getConnection());
    }
References datastorage.ConnectionBuilder.getConnection().
Referenced by controller.NewTreatmentController.createComboBoxDataCaregiver(), controller.TreatmentController.initializeController(), and controller.AllCaregiverController.readAllAndShowInTableView().
createPatientDAO()
PatientDAO datastorage.DAOFactory.createPatientDAO ()
creates a new instance of the PatientDAO
Returns
instance of the PatientDAO
{
        return new PatientDAO(ConnectionBuilder.getConnection());
    }
References datastorage.ConnectionBuilder.getConnection().
Referenced by controller.AllTreatmentController.createComboBoxDataPatient(), controller.TreatmentController.initializeController(), and controller.AllPatientController.readAllAndShowInTableView().
createTreatmentDAO()
TreatmentDAO datastorage.DAOFactory.createTreatmentDAO ()
creates a new instance of the TreatmentDAO
Returns
instance of the TreatmentDAO
{
        return new TreatmentDAO(ConnectionBuilder.getConnection());
    }
References datastorage.ConnectionBuilder.getConnection().
Referenced by controller.NewTreatmentController.createTreatment(), controller.TreatmentController.doUpdate(), controller.AllPatientController.handleBlockRow(), controller.AllTreatmentController.handleComboBox(), controller.AllTreatmentController.handleDelete(), controller.AllCaregiverController.handleDeleteRow(), controller.AllPatientController.handleDeleteRow(), and controller.AllTreatmentController.readAllAndShowInTableView().
getDAOFactory()
static DAOFactory datastorage.DAOFactory.getDAOFactory () static
Singleton which instantiates a new Object of this class if none already exists.
Returns
instance of a new object of this class
{
        if (instance == null) {
            instance = new DAOFactory();
        }
        return instance;
    }
References datastorage.DAOFactory.DAOFactory(), and datastorage.DAOFactory.instance.
Referenced by controller.NewTreatmentController.createComboBoxDataCaregiver(), controller.AllTreatmentController.createComboBoxDataPatient(), controller.NewTreatmentController.createTreatment(), controller.TreatmentController.doUpdate(), controller.AllPatientController.handleBlockRow(), controller.AllTreatmentController.handleComboBox(), controller.AllTreatmentController.handleDelete(), controller.AllCaregiverController.handleDeleteRow(), controller.AllPatientController.handleDeleteRow(), controller.TreatmentController.initializeController(), controller.AllCaregiverController.readAllAndShowInTableView(), controller.AllPatientController.readAllAndShowInTableView(), and controller.AllTreatmentController.readAllAndShowInTableView().
Member Data Documentation
instance
DAOFactory datastorage.DAOFactory.instance static private
Referenced by datastorage.DAOFactory.getDAOFactory().
The documentation for this class was generated from the following file:
src/main/java/datastorage/DAOFactory.java