Nursing home student: controller.LoginWindowController Class Reference
controller.LoginWindowController Class Reference
Package Attributes
TextField txtUsername
TextField txtPassword
Private Member Functions
void handleLogin (ActionEvent e)
Private Attributes
BorderPane mainBorderPane
Detailed Description
The LoginWindowController contains the entire logic of the login view. It determines which data is displayed and how to react to events.
Definition at line 18 of file LoginWindowController.java.
Member Function Documentation
handleLogin()
void controller.LoginWindowController.handleLogin (ActionEvent e) private
handles a login-click-event. Checks the user credentials and changes the window to the main view if the credentials are correct else wise shows an alert. On successful login loads the MainWindowView
Definition at line 34 of file LoginWindowController.java.
{
        UserManager.getInstance().Login(txtUsername.getText(), txtPassword.getText());
        if(UserManager.getInstance().isLoggedIn()) {
            FXMLLoader loader = new FXMLLoader(Main.class.getResource("/MainWindowView.fxml"));
            try {
                mainBorderPane.setCenter(loader.load());
            } catch (IOException ex) {
                ex.printStackTrace();
            }
            MainWindowController controller = loader.getController();
        } else {
            Alert alert = new Alert(Alert.AlertType.ERROR);
            alert.setHeaderText("Password or Username was incorrect");
            alert.showAndWait();
        }
    }
References account.UserManager.getInstance(), account.UserManager.isLoggedIn(), account.UserManager.Login(), controller.LoginWindowController.mainBorderPane, controller.LoginWindowController.txtPassword, and controller.LoginWindowController.txtUsername.
Member Data Documentation
mainBorderPane
BorderPane controller.LoginWindowController.mainBorderPane private
Definition at line 21 of file LoginWindowController.java.
Referenced by controller.LoginWindowController.handleLogin().
txtPassword
TextField controller.LoginWindowController.txtPassword package
Definition at line 27 of file LoginWindowController.java.
Referenced by controller.LoginWindowController.handleLogin().
txtUsername
TextField controller.LoginWindowController.txtUsername package
Definition at line 24 of file LoginWindowController.java.
Referenced by controller.LoginWindowController.handleLogin().
The documentation for this class was generated from the following file:
src/main/java/controller/LoginWindowController.java