Nursing home student: model.Treatment Class Reference
model.Treatment Class Reference
Public Member Functions
Treatment (long pid, long cid, LocalDate date, LocalTime begin, LocalTime end, String description, String remarks, boolean shown)
Treatment (long tid, long pid, long cid, LocalDate date, LocalTime begin, LocalTime end, String description, String remarks, boolean shown)
long getTid ()
long getPid ()
long getCid ()
String getDate ()
String getBegin ()
String getEnd ()
void setDate (String s_date)
void setBegin (String begin)
void setEnd (String end)
String getDescription ()
void setDescription (String description)
String getRemarks ()
void setRemarks (String remarks)
boolean isShown ()
void setShown (boolean shown)
String toString ()
Private Attributes
long tid
long pid
long cid
LocalDate date
LocalTime begin
LocalTime end
String description
String remarks
boolean shown
Detailed Description
Treatments are the work the caregivers do to the patients.
Definition at line 10 of file Treatment.java.
Constructor & Destructor Documentation
Treatment() [1/2]
model.Treatment.Treatment (long pid, long cid, LocalDate date, LocalTime begin, LocalTime end, String description, String remarks, boolean shown)
constructs a treatment from the given params.
Parameters
pid
cid
date
begin
end
description
remarks
shown
Definition at line 32 of file Treatment.java.
{
        this.pid = pid;
        this.cid = cid;
        this.date = date;
        this.begin = begin;
        this.end = end;
        this.description = description;
        this.remarks = remarks;
        this.shown = shown;
    }
References model.Treatment.begin, model.Treatment.cid, model.Treatment.date, model.Treatment.description, model.Treatment.end, model.Treatment.pid, model.Treatment.remarks, and model.Treatment.shown.
Treatment() [2/2]
model.Treatment.Treatment (long tid, long pid, long cid, LocalDate date, LocalTime begin, LocalTime end, String description, String remarks, boolean shown)
constructs a treatment from the given params.
Parameters
tid
pid
cid
date
begin
end
description
remarks
shown
Definition at line 56 of file Treatment.java.
{
        this.tid = tid;
        this.pid = pid;
        this.cid = cid;
        this.date = date;
        this.begin = begin;
        this.end = end;
        this.description = description;
        this.remarks = remarks;
        this.shown = shown;
    }
References model.Treatment.begin, model.Treatment.cid, model.Treatment.date, model.Treatment.description, model.Treatment.end, model.Treatment.pid, model.Treatment.remarks, model.Treatment.shown, and model.Treatment.tid.
Member Function Documentation
getBegin()
String model.Treatment.getBegin ()
Returns
begin time of the treatment as a String
Definition at line 103 of file Treatment.java.
{
        return begin.toString();
    }
References model.Treatment.begin.
Referenced by datastorage.TreatmentDAO.getCreateStatementString(), datastorage.TreatmentDAO.getUpdateStatementString(), and controller.TreatmentController.showData().
getCid()
long model.Treatment.getCid ()
Returns
caregiver id
Definition at line 89 of file Treatment.java.
{
        return this.cid;
    }
References model.Treatment.cid.
Referenced by datastorage.TreatmentDAO.getCreateStatementString(), datastorage.TreatmentDAO.getUpdateStatementString(), and controller.TreatmentController.initializeController().
getDate()
String model.Treatment.getDate ()
Returns
date as a String
Definition at line 96 of file Treatment.java.
{
        return date.toString();
    }
References model.Treatment.date.
Referenced by datastorage.TreatmentDAO.getCreateStatementString(), datastorage.TreatmentDAO.getUpdateStatementString(), and controller.TreatmentController.showData().
getDescription()
String model.Treatment.getDescription ()
Returns
description
Definition at line 144 of file Treatment.java.
{
        return description;
    }
References model.Treatment.description.
Referenced by datastorage.TreatmentDAO.getCreateStatementString(), datastorage.TreatmentDAO.getUpdateStatementString(), and controller.TreatmentController.showData().
getEnd()
String model.Treatment.getEnd ()
Returns
end time of the treatment as a String
Definition at line 110 of file Treatment.java.
{
        return end.toString();
    }
References model.Treatment.end.
Referenced by datastorage.TreatmentDAO.getCreateStatementString(), datastorage.TreatmentDAO.getUpdateStatementString(), and controller.TreatmentController.showData().
getPid()
long model.Treatment.getPid ()
Returns
patient id
Definition at line 81 of file Treatment.java.
{
        return this.pid;
    }
References model.Treatment.pid.
Referenced by datastorage.TreatmentDAO.getCreateStatementString(), datastorage.TreatmentDAO.getUpdateStatementString(), and controller.TreatmentController.initializeController().
getRemarks()
String model.Treatment.getRemarks ()
Returns
remarks
Definition at line 158 of file Treatment.java.
{
        return remarks;
    }
References model.Treatment.remarks.
Referenced by datastorage.TreatmentDAO.getCreateStatementString(), datastorage.TreatmentDAO.getUpdateStatementString(), and controller.TreatmentController.showData().
getTid()
long model.Treatment.getTid ()
Returns
treatment id
Definition at line 73 of file Treatment.java.
{
        return tid;
    }
References model.Treatment.tid.
Referenced by datastorage.TreatmentDAO.getUpdateStatementString(), and controller.AllTreatmentController.handleDelete().
isShown()
boolean model.Treatment.isShown ()
Returns
shown
Definition at line 172 of file Treatment.java.
{
        return shown;
    }
References model.Treatment.shown.
Referenced by datastorage.TreatmentDAO.getUpdateStatementString().
setBegin()
void model.Treatment.setBegin (String begin)
convert given param to a localDate and store as new begin
Parameters
begin as string
Definition at line 127 of file Treatment.java.
{
        LocalTime time = DateConverter.convertStringToLocalTime(begin);
        this.begin = time;
    }
References model.Treatment.begin, and utils.DateConverter.convertStringToLocalTime().
Referenced by controller.TreatmentController.handleChange().
setDate()
void model.Treatment.setDate (String s_date)
convert given param to a localDate and store as new date
Parameters
s_date as string
Definition at line 118 of file Treatment.java.
{
        LocalDate date = DateConverter.convertStringToLocalDate(s_date);
        this.date = date;
    }
References utils.DateConverter.convertStringToLocalDate(), and model.Treatment.date.
Referenced by controller.TreatmentController.handleChange().
setDescription()
void model.Treatment.setDescription (String description)
Parameters
description new description
Definition at line 151 of file Treatment.java.
{
        this.description = description;
    }
References model.Treatment.description.
Referenced by controller.TreatmentController.handleChange().
setEnd()
void model.Treatment.setEnd (String end)
convert given param to a localDate and store as new end
Parameters
end as string
Definition at line 136 of file Treatment.java.
{
        LocalTime time = DateConverter.convertStringToLocalTime(end);
        this.end = time;
    }
References utils.DateConverter.convertStringToLocalTime(), and model.Treatment.end.
Referenced by controller.TreatmentController.handleChange().
setRemarks()
void model.Treatment.setRemarks (String remarks)
Parameters
remarks new remarks
Definition at line 165 of file Treatment.java.
{
        this.remarks = remarks;
    }
References model.Treatment.remarks.
Referenced by controller.TreatmentController.handleChange().
setShown()
void model.Treatment.setShown (boolean shown)
Parameters
shown new shown
Definition at line 179 of file Treatment.java.
{
        this.shown = shown;
    }
References model.Treatment.shown.
Referenced by controller.AllTreatmentController.handleBlockRow().
toString()
String model.Treatment.toString ()
Returns
string-representation of the treatment
Definition at line 186 of file Treatment.java.
{
        return "\nBehandlung" + "\nTID: " + this.tid +
                "\nPID: " + this.pid +
                "\nDate: " + this.date +
                "\nBegin: " + this.begin +
                "\nEnd: " + this.end +
                "\nDescription: " + this.description +
                "\nRemarks: " + this.remarks + "\n";
    }
Member Data Documentation
begin
LocalTime model.Treatment.begin private
Definition at line 15 of file Treatment.java.
Referenced by model.Treatment.getBegin(), model.Treatment.setBegin(), and model.Treatment.Treatment().
cid
long model.Treatment.cid private
Definition at line 13 of file Treatment.java.
Referenced by model.Treatment.getCid(), and model.Treatment.Treatment().
date
LocalDate model.Treatment.date private
Definition at line 14 of file Treatment.java.
Referenced by model.Treatment.getDate(), model.Treatment.setDate(), and model.Treatment.Treatment().
description
String model.Treatment.description private
Definition at line 17 of file Treatment.java.
Referenced by model.Treatment.getDescription(), model.Treatment.setDescription(), and model.Treatment.Treatment().
end
LocalTime model.Treatment.end private
Definition at line 16 of file Treatment.java.
Referenced by model.Treatment.getEnd(), model.Treatment.setEnd(), and model.Treatment.Treatment().
pid
long model.Treatment.pid private
Definition at line 12 of file Treatment.java.
Referenced by model.Treatment.getPid(), and model.Treatment.Treatment().
remarks
String model.Treatment.remarks private
Definition at line 18 of file Treatment.java.
Referenced by model.Treatment.getRemarks(), model.Treatment.setRemarks(), and model.Treatment.Treatment().
shown
boolean model.Treatment.shown private
Definition at line 19 of file Treatment.java.
Referenced by model.Treatment.isShown(), model.Treatment.setShown(), and model.Treatment.Treatment().
tid
long model.Treatment.tid private
Definition at line 11 of file Treatment.java.
Referenced by model.Treatment.getTid(), and model.Treatment.Treatment().
The documentation for this class was generated from the following file:
src/main/java/model/Treatment.java