Nursing home student: datastorage.TreatmentDAO Class Reference
datastorage.TreatmentDAO Class Reference
Public Member Functions
TreatmentDAO (Connection conn)
List< Treatment > readTreatmentsByPid (long pid) throws SQLException
void deleteByPid (long key) throws SQLException
Public Member Functions inherited from datastorage.DAOimp< Treatment >
DAOimp (Connection conn)
void create (T t) throws SQLException
T read (long key) throws SQLException
List< T > readAll () throws SQLException
List< T > readAllUnblocked () throws SQLException
void update (T t) throws SQLException
void deleteById (long key) throws SQLException
Connection getConn ()
Protected Member Functions
String getCreateStatementString (Treatment treatment)
String getReadByIDStatementString (long key)
Treatment getInstanceFromResultSet (ResultSet result) throws SQLException
String getReadAllStatementString ()
String getReadAllUnblockedStatementString ()
ArrayList< Treatment > getListFromResultSet (ResultSet result) throws SQLException
String getUpdateStatementString (Treatment treatment)
String getDeleteStatementString (long key)
Protected Member Functions inherited from datastorage.DAOimp< Treatment >
abstract String getCreateStatementString (T t)
abstract String getReadByIDStatementString (long key)
abstract T getInstanceFromResultSet (ResultSet set) throws SQLException
abstract String getReadAllStatementString ()
abstract String getReadAllUnblockedStatementString ()
abstract ArrayList< T > getListFromResultSet (ResultSet set) throws SQLException
abstract String getUpdateStatementString (T t)
abstract String getDeleteStatementString (long key)
Private Member Functions
String getReadAllTreatmentsOfOnePatientByPid (long pid)
Additional Inherited Members
Protected Attributes inherited from datastorage.DAOimp< Treatment >
Connection conn
Detailed Description
Implements the Interface DAOImp. Overrides methods to generate specific treatment-SQL-queries.
Definition at line 19 of file TreatmentDAO.java.
Constructor & Destructor Documentation
TreatmentDAO()
datastorage.TreatmentDAO.TreatmentDAO (Connection conn)
constructs Object. Calls the Constructor from DAOImp to store the connection.
Parameters
conn
Definition at line 25 of file TreatmentDAO.java.
{
        super(conn);
    }
References datastorage.DAOimp< Treatment >.conn.
Member Function Documentation
deleteByPid()
void datastorage.TreatmentDAO.deleteByPid (long key) throws SQLException
generates a delete-Statement for a given key
Parameters
key of the id of a patient for which a specific DELETE is to be executed
Exceptions
SQLException
Definition at line 160 of file TreatmentDAO.java.
{
        Statement st = conn.createStatement();
        st.executeUpdate(String.format("Delete FROM treatment WHERE pid= %d", key));
    }
References datastorage.DAOimp< Treatment >.conn.
Referenced by controller.AllCaregiverController.handleDeleteRow(), and controller.AllPatientController.handleDeleteRow().
getCreateStatementString()
String datastorage.TreatmentDAO.getCreateStatementString (Treatment treatment) protected
generates a INSERT INTO-Statement for a given treatment
Parameters
treatment for which a specific INSERT INTO is to be created
Returns
String with the generated SQL.
Definition at line 35 of file TreatmentDAO.java.
{
        return String.format("INSERT INTO treatment (pid, cid, treatment_date, begin, end, description, remarks, show, blockeddate) VALUES " +
                "(%d, '%s', '%s', '%s', '%s', '%s', '%s', '%s', %s)", treatment.getPid(), treatment.getCid(), treatment.getDate(),
                treatment.getBegin(), treatment.getEnd(), treatment.getDescription(),
                treatment.getRemarks(), true, null);
    }
References model.Treatment.getBegin(), model.Treatment.getCid(), model.Treatment.getDate(), model.Treatment.getDescription(), model.Treatment.getEnd(), model.Treatment.getPid(), and model.Treatment.getRemarks().
getDeleteStatementString()
String datastorage.TreatmentDAO.getDeleteStatementString (long key) protected
generates a delete-Statement for a given key
Parameters
key for which a specific DELETE is to be created
Returns
String with the generated SQL.
Definition at line 127 of file TreatmentDAO.java.
{
        return String.format("Delete FROM treatment WHERE tid= %d", key);
    }
getInstanceFromResultSet()
Treatment datastorage.TreatmentDAO.getInstanceFromResultSet (ResultSet result) throws SQLException protected
maps a ResultSet to a Treatment
Parameters
result ResultSet with a single row. Columns will be mapped to a treatment-object.
Returns
treatment with the data from the resultSet.
Definition at line 58 of file TreatmentDAO.java.
{
        LocalDate date = DateConverter.convertStringToLocalDate(result.getString(3));
        LocalTime begin = DateConverter.convertStringToLocalTime(result.getString(4));
        LocalTime end = DateConverter.convertStringToLocalTime(result.getString(5));
        Treatment m = new Treatment(result.getLong(1),result.getLong(2),
                result.getLong(8), date, begin, end, result.getString(6),
                result.getString(7), result.getBoolean(9));
        return m;
    }
References utils.DateConverter.convertStringToLocalDate(), and utils.DateConverter.convertStringToLocalTime().
getListFromResultSet()
ArrayList< Treatment > datastorage.TreatmentDAO.getListFromResultSet (ResultSet result) throws SQLException protected
maps a ResultSet to a Treatment-List
Parameters
result ResultSet with a multiple rows. Data will be mapped to treatment-object.
Returns
ArrayList with treatments from the resultSet.
Definition at line 92 of file TreatmentDAO.java.
{
        ArrayList<Treatment> list = new ArrayList<Treatment>();
        Treatment t = null;
        while (result.next()) {
            LocalDate date = DateConverter.convertStringToLocalDate(result.getString(3));
            LocalTime begin = DateConverter.convertStringToLocalTime(result.getString(4));
            LocalTime end = DateConverter.convertStringToLocalTime(result.getString(5));
            t = new Treatment(result.getLong(1), result.getLong(2),
                    result.getLong(8), date, begin, end, result.getString(6),
                    result.getString(7), result.getBoolean(9));
            list.add(t);
        }
        return list;
    }
References utils.DateConverter.convertStringToLocalDate(), and utils.DateConverter.convertStringToLocalTime().
Referenced by datastorage.TreatmentDAO.readTreatmentsByPid().
getReadAllStatementString()
String datastorage.TreatmentDAO.getReadAllStatementString () protected
generates a SELECT-Statement for all treatments.
Returns
String with the generated SQL.
Definition at line 73 of file TreatmentDAO.java.
{
        return "SELECT * FROM treatment";
    }
getReadAllTreatmentsOfOnePatientByPid()
String datastorage.TreatmentDAO.getReadAllTreatmentsOfOnePatientByPid (long pid) private
generates a SELECT-Statement for all treatments, where the pid matches the given id of the patient.
Parameters
pid pid id of the patient
Returns
String with the generated SQL.
Definition at line 151 of file TreatmentDAO.java.
{
        return String.format("SELECT * FROM treatment WHERE pid = %d", pid);
    }
Referenced by datastorage.TreatmentDAO.readTreatmentsByPid().
getReadAllUnblockedStatementString()
String datastorage.TreatmentDAO.getReadAllUnblockedStatementString () protected
generates a SELECT-Statement for all treatments, where the show variable is true.
Returns
String with the generated SQL.
Definition at line 82 of file TreatmentDAO.java.
{
        return "SELECT * FROM treatment WHERE show = true";
    }
getReadByIDStatementString()
String datastorage.TreatmentDAO.getReadByIDStatementString (long key) protected
generates a select-Statement for a given key
Parameters
key for which a specific SELECT is to be created
Returns
String with the generated SQL.
Definition at line 48 of file TreatmentDAO.java.
{
        return String.format("SELECT * FROM treatment WHERE tid = %d", key);
    }
getUpdateStatementString()
String datastorage.TreatmentDAO.getUpdateStatementString (Treatment treatment) protected
generates a UPDATE-Statement for a given treatment
Parameters
treatment for which a specific update is to be created
Returns
String with the generated SQL.
Definition at line 113 of file TreatmentDAO.java.
{
        return String.format("UPDATE treatment SET pid = %d, cid = %d, treatment_date ='%s', begin = '%s', end = '%s'," +
                "description = '%s', remarks = '%s', show = '%s', blockeddate = %s WHERE tid = %d", treatment.getPid(), treatment.getCid(), treatment.getDate(),
                treatment.getBegin(), treatment.getEnd(), treatment.getDescription(), treatment.getRemarks(), treatment.isShown(),
                treatment.isShown() ? "NULL" : "'" + new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime()) + "'",
                treatment.getTid());
    }
References model.Treatment.getBegin(), model.Treatment.getCid(), model.Treatment.getDate(), model.Treatment.getDescription(), model.Treatment.getEnd(), model.Treatment.getPid(), model.Treatment.getRemarks(), model.Treatment.getTid(), and model.Treatment.isShown().
readTreatmentsByPid()
List< Treatment > datastorage.TreatmentDAO.readTreatmentsByPid (long pid) throws SQLException
calls getReadAllTreatmentsOfOnePatientByPid method, with given pid
Parameters
pid id of the patient
Returns
list of Treatments
Exceptions
SQLException
Definition at line 137 of file TreatmentDAO.java.
{
        ArrayList<Treatment> list = new ArrayList<Treatment>();
        Treatment object = null;
        Statement st = conn.createStatement();
        ResultSet result = st.executeQuery(getReadAllTreatmentsOfOnePatientByPid(pid));
        list = getListFromResultSet(result);
        return list;
    }
References datastorage.DAOimp< Treatment >.conn, datastorage.TreatmentDAO.getListFromResultSet(), and datastorage.TreatmentDAO.getReadAllTreatmentsOfOnePatientByPid().
Referenced by controller.AllPatientController.handleBlockRow(), and controller.AllTreatmentController.handleComboBox().
The documentation for this class was generated from the following file:
src/main/java/datastorage/TreatmentDAO.java