Nursing home student: datastorage.PatientDAO Class Reference
datastorage.PatientDAO Class Reference
Public Member Functions
PatientDAO (Connection conn)
Public Member Functions inherited from datastorage.DAOimp< Patient >
DAOimp (Connection conn)
void create (T t) throws SQLException
T read (long key) throws SQLException
List< T > readAll () throws SQLException
List< T > readAllUnblocked () throws SQLException
void update (T t) throws SQLException
void deleteById (long key) throws SQLException
Connection getConn ()
Protected Member Functions
String getCreateStatementString (Patient patient)
String getReadByIDStatementString (long key)
Patient getInstanceFromResultSet (ResultSet result) throws SQLException
String getReadAllStatementString ()
String getReadAllUnblockedStatementString ()
ArrayList< Patient > getListFromResultSet (ResultSet result) throws SQLException
String getUpdateStatementString (Patient patient)
String getDeleteStatementString (long key)
Protected Member Functions inherited from datastorage.DAOimp< Patient >
abstract String getCreateStatementString (T t)
abstract String getReadByIDStatementString (long key)
abstract T getInstanceFromResultSet (ResultSet set) throws SQLException
abstract String getReadAllStatementString ()
abstract String getReadAllUnblockedStatementString ()
abstract ArrayList< T > getListFromResultSet (ResultSet set) throws SQLException
abstract String getUpdateStatementString (T t)
abstract String getDeleteStatementString (long key)
Additional Inherited Members
Protected Attributes inherited from datastorage.DAOimp< Patient >
Connection conn
Detailed Description
Implements the Interface DAOImp. Overrides methods to generate specific patient-SQL-queries.
Definition at line 19 of file PatientDAO.java.
Constructor & Destructor Documentation
PatientDAO()
datastorage.PatientDAO.PatientDAO (Connection conn)
constructs Object. Calls the Constructor from DAOImp to store the connection.
Parameters
conn
Definition at line 25 of file PatientDAO.java.
{
        super(conn);
    }
References datastorage.DAOimp< Patient >.conn.
Member Function Documentation
getCreateStatementString()
String datastorage.PatientDAO.getCreateStatementString (Patient patient) protected
generates a INSERT INTO-Statement for a given patient
Parameters
patient for which a specific INSERT INTO is to be created
Returns
String with the generated SQL.
Definition at line 35 of file PatientDAO.java.
{
        return String.format("INSERT INTO patient (firstname, surname, dateOfBirth, carelevel, roomnumber, show, blockeddate) VALUES ('%s', '%s', '%s', '%s', '%s', '%s', %s)",
                patient.getFirstName(), patient.getSurname(), patient.getDateOfBirth(), patient.getCareLevel(), patient.getRoomnumber(), true, null);
    }
References model.Patient.getCareLevel(), model.Patient.getDateOfBirth(), model.Person.getFirstName(), model.Patient.getRoomnumber(), and model.Person.getSurname().
getDeleteStatementString()
String datastorage.PatientDAO.getDeleteStatementString (long key) protected
generates a delete-Statement for a given key
Parameters
key for which a specific DELETE is to be created
Returns
String with the generated SQL.
Definition at line 121 of file PatientDAO.java.
{
        return String.format("Delete FROM patient WHERE pid=%d", key);
    }
getInstanceFromResultSet()
Patient datastorage.PatientDAO.getInstanceFromResultSet (ResultSet result) throws SQLException protected
maps a ResultSet to a Patient
Parameters
result ResultSet with a single row. Columns will be mapped to a patient-object.
Returns
patient with the data from the resultSet.
Definition at line 56 of file PatientDAO.java.
{
        Patient p = null;
        LocalDate date = DateConverter.convertStringToLocalDate(result.getString(4));
        p = new Patient(result.getInt(1), result.getString(2),
                result.getString(3), date, result.getString(5),
                result.getString(6), result.getBoolean(7));
        return p;
    }
References utils.DateConverter.convertStringToLocalDate().
getListFromResultSet()
ArrayList< Patient > datastorage.PatientDAO.getListFromResultSet (ResultSet result) throws SQLException protected
maps a ResultSet to a Patient-List
Parameters
result ResultSet with a multiple rows. Data will be mapped to patient-object.
Returns
ArrayList with patients from the resultSet.
Definition at line 89 of file PatientDAO.java.
{
        ArrayList<Patient> list = new ArrayList<Patient>();
        Patient p = null;
        while (result.next()) {
            LocalDate date = DateConverter.convertStringToLocalDate(result.getString(4));
            p = new Patient(result.getInt(1), result.getString(2),
                    result.getString(3), date,
                    result.getString(5), result.getString(6), result.getBoolean(7));
            list.add(p);
        }
        return list;
    }
References utils.DateConverter.convertStringToLocalDate().
getReadAllStatementString()
String datastorage.PatientDAO.getReadAllStatementString () protected
generates a SELECT-Statement for all patients.
Returns
String with the generated SQL.
Definition at line 70 of file PatientDAO.java.
{
        return "SELECT * FROM patient";
    }
getReadAllUnblockedStatementString()
String datastorage.PatientDAO.getReadAllUnblockedStatementString () protected
generates a SELECT-Statement for all patients, where the show variable is true.
Returns
String with the generated SQL.
Definition at line 79 of file PatientDAO.java.
{
        return "SELECT * FROM patient WHERE SHOW = TRUE";
    }
getReadByIDStatementString()
String datastorage.PatientDAO.getReadByIDStatementString (long key) protected
generates a select-Statement for a given key
Parameters
key for which a specific SELECT is to be created
Returns
String with the generated SQL.
Definition at line 46 of file PatientDAO.java.
{
        return String.format("SELECT * FROM patient WHERE pid = %d AND SHOW = TRUE", key);
    }
getUpdateStatementString()
String datastorage.PatientDAO.getUpdateStatementString (Patient patient) protected
generates a UPDATE-Statement for a given patient
Parameters
patient for which a specific update is to be created
Returns
String with the generated SQL.
Definition at line 108 of file PatientDAO.java.
{
        return String.format("UPDATE patient SET firstname = '%s', surname = '%s', dateOfBirth = '%s', carelevel = '%s', " +
                "roomnumber = '%s', show = '%s', blockeddate = %s WHERE pid = '%d'", patient.getFirstName(), patient.getSurname(), patient.getDateOfBirth(),
                patient.getCareLevel(), patient.getRoomnumber(), patient.Shown(),
                patient.Shown() ? "NULL" : "'" + new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime()) + "'", patient.getPid());
    }
References model.Patient.getCareLevel(), model.Patient.getDateOfBirth(), model.Person.getFirstName(), model.Patient.getPid(), model.Patient.getRoomnumber(), model.Person.getSurname(), and model.Patient.Shown().
The documentation for this class was generated from the following file:
src/main/java/datastorage/PatientDAO.java