Nursing home student: controller.AllCaregiverController Class Reference
controller.AllCaregiverController Class Reference
Public Member Functions
void initialize ()
void handleOnEditFirstname (TableColumn.CellEditEvent< Caregiver, String > event)
void handleOnEditSurname (TableColumn.CellEditEvent< Caregiver, String > event)
void handleOnEditTelephone (TableColumn.CellEditEvent< Caregiver, String > event)
void handleBlockRow ()
void handleDeleteRow ()
void handleAdd ()
Package Attributes
Button btnDelete
Button btnAdd
TextField txfSurname
TextField txfFirstname
TextField txfTelephone
Private Member Functions
void doUpdate (TableColumn.CellEditEvent< Caregiver, String > t)
void readAllAndShowInTableView ()
void clearTextfields ()
Private Attributes
TableView< Caregiver > tableView
TableColumn< Caregiver, Integer > colID
TableColumn< Caregiver, String > colFirstName
TableColumn< Caregiver, String > colSurname
TableColumn< Caregiver, String > colTelephone
ObservableList< Caregiver > tableviewContent = FXCollections.observableArrayList()
CaregiverDAO dao
Detailed Description
The AllCaregiverController contains the entire logic of the caregiver view. It determines which data is displayed and how to react to events.
Definition at line 26 of file AllCaregiverController.java.
Member Function Documentation
clearTextfields()
void controller.AllCaregiverController.clearTextfields () private
removes content from all textfields
Definition at line 196 of file AllCaregiverController.java.
{
        this.txfFirstname.clear();
        this.txfSurname.clear();
        this.txfTelephone.clear();
    }
Referenced by controller.AllCaregiverController.handleAdd().
doUpdate()
void controller.AllCaregiverController.doUpdate (TableColumn.CellEditEvent< Caregiver, String > t) private
updates a caregiver by calling the update-Method in the CaregiverDAO
Parameters
t row to be updated by the user (includes the caregiver)
Definition at line 116 of file AllCaregiverController.java.
{
        try {
            dao.update(t.getRowValue());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References controller.AllCaregiverController.dao, and datastorage.DAOimp< T >.update().
Referenced by controller.AllCaregiverController.handleOnEditFirstname(), controller.AllCaregiverController.handleOnEditSurname(), and controller.AllCaregiverController.handleOnEditTelephone().
handleAdd()
void controller.AllCaregiverController.handleAdd ()
handles an add-click-event. Creates a patient and calls the create method in the CaregiverDAO
Definition at line 176 of file AllCaregiverController.java.
{
        String surname = this.txfSurname.getText();
        String firstname = this.txfFirstname.getText();
        String telephone = this.txfTelephone.getText();
        if(telephone.equals("") || firstname.equals("") || surname.equals("")) {
            return;
        }
        try {
            Caregiver caregiver = new Caregiver(firstname, surname, telephone, true);
            dao.create(caregiver);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        readAllAndShowInTableView();
        clearTextfields();
    }
References controller.AllCaregiverController.clearTextfields(), datastorage.DAOimp< T >.create(), controller.AllCaregiverController.dao, and controller.AllCaregiverController.readAllAndShowInTableView().
handleBlockRow()
void controller.AllCaregiverController.handleBlockRow ()
handles a block-click-event. Changes the shown variable of the patient in the database to indicate if this caregiver should be shown
Definition at line 145 of file AllCaregiverController.java.
{
        Caregiver selectedItem = this.tableView.getSelectionModel().getSelectedItem();
        try {
            selectedItem.setShown(false);
            dao.update(selectedItem);
            this.tableView.getItems().remove(selectedItem);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References controller.AllCaregiverController.dao, model.Caregiver.setShown(), and datastorage.DAOimp< T >.update().
handleDeleteRow()
void controller.AllCaregiverController.handleDeleteRow ()
handles a delete-click-event. Calls the delete methods in the PatientDAO and TreatmentDAO
Definition at line 160 of file AllCaregiverController.java.
{
        TreatmentDAO tDao = DAOFactory.getDAOFactory().createTreatmentDAO();
        Caregiver selectedItem = this.tableView.getSelectionModel().getSelectedItem();
        try {
            tDao.deleteByPid(selectedItem.getId());
            dao.deleteById(selectedItem.getId());
            this.tableView.getItems().remove(selectedItem);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.DAOFactory.createTreatmentDAO(), controller.AllCaregiverController.dao, datastorage.DAOimp< T >.deleteById(), datastorage.TreatmentDAO.deleteByPid(), datastorage.DAOFactory.getDAOFactory(), and model.Caregiver.getId().
handleOnEditFirstname()
void controller.AllCaregiverController.handleOnEditFirstname (TableColumn.CellEditEvent< Caregiver, String > event)
handles new firstname value
Parameters
event event including the value that a user entered into the cell
Definition at line 87 of file AllCaregiverController.java.
{
        event.getRowValue().setFirstName(event.getNewValue());
        doUpdate(event);
    }
References controller.AllCaregiverController.doUpdate().
handleOnEditSurname()
void controller.AllCaregiverController.handleOnEditSurname (TableColumn.CellEditEvent< Caregiver, String > event)
handles new surname value
Parameters
event event including the value that a user entered into the cell
Definition at line 97 of file AllCaregiverController.java.
{
        event.getRowValue().setSurname(event.getNewValue());
        doUpdate(event);
    }
References controller.AllCaregiverController.doUpdate().
handleOnEditTelephone()
void controller.AllCaregiverController.handleOnEditTelephone (TableColumn.CellEditEvent< Caregiver, String > event)
handles new telephone value
Parameters
event event including the value that a user entered into the cell
Definition at line 107 of file AllCaregiverController.java.
{
        event.getRowValue().setTelephone(event.getNewValue());
        doUpdate(event);
    }
References controller.AllCaregiverController.doUpdate().
initialize()
void controller.AllCaregiverController.initialize ()
Initializes the corresponding fields. Is called as soon as the corresponding FXML file is to be displayed.
Definition at line 55 of file AllCaregiverController.java.
{
        readAllAndShowInTableView();
        this.colID.setCellValueFactory(new PropertyValueFactory<Caregiver, Integer>("id"));
        //CellValuefactory zum Anzeigen der Daten in der TableView
        this.colFirstName.setCellValueFactory(new PropertyValueFactory<Caregiver, String>("firstName"));
        //CellFactory zum Schreiben innerhalb der Tabelle
        this.colFirstName.setCellFactory(TextFieldTableCell.forTableColumn());
        this.colSurname.setCellValueFactory(new PropertyValueFactory<Caregiver, String>("surname"));
        this.colSurname.setCellFactory(TextFieldTableCell.forTableColumn());
        this.colTelephone.setCellValueFactory(new PropertyValueFactory<Caregiver, String>("telephone"));
        this.colTelephone.setCellFactory(TextFieldTableCell.forTableColumn());
        //Anzeigen der Daten
        this.tableView.setItems(this.tableviewContent);
        try {
            Statement statement = dao.getConn().createStatement();
            statement.executeQuery("DELETE FROM caregiver WHERE show = FALSE AND blockeddate <= DATEADD('YEAR', -10, CURRENT_DATE);");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
References controller.AllCaregiverController.dao, datastorage.DAOimp< T >.getConn(), and controller.AllCaregiverController.readAllAndShowInTableView().
readAllAndShowInTableView()
void controller.AllCaregiverController.readAllAndShowInTableView () private
calls readAll in CaregiverDAO and shows patients in the table
Definition at line 127 of file AllCaregiverController.java.
{
        this.tableviewContent.clear();
        this.dao = DAOFactory.getDAOFactory().createCaregiverDAO();
        List<Caregiver> allCaregivers;
        try {
            allCaregivers = dao.readAllUnblocked();
            for (Caregiver p : allCaregivers) {
                this.tableviewContent.add(p);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.DAOFactory.createCaregiverDAO(), controller.AllCaregiverController.dao, datastorage.DAOFactory.getDAOFactory(), and datastorage.DAOimp< T >.readAllUnblocked().
Referenced by controller.AllCaregiverController.handleAdd(), and controller.AllCaregiverController.initialize().
Member Data Documentation
btnAdd
Button controller.AllCaregiverController.btnAdd package
Definition at line 41 of file AllCaregiverController.java.
btnDelete
Button controller.AllCaregiverController.btnDelete package
Definition at line 39 of file AllCaregiverController.java.
colFirstName
TableColumn<Caregiver, String> controller.AllCaregiverController.colFirstName private
Definition at line 32 of file AllCaregiverController.java.
colID
TableColumn<Caregiver, Integer> controller.AllCaregiverController.colID private
Definition at line 30 of file AllCaregiverController.java.
colSurname
TableColumn<Caregiver, String> controller.AllCaregiverController.colSurname private
Definition at line 34 of file AllCaregiverController.java.
colTelephone
TableColumn<Caregiver, String> controller.AllCaregiverController.colTelephone private
Definition at line 36 of file AllCaregiverController.java.
dao
CaregiverDAO controller.AllCaregiverController.dao private
Definition at line 50 of file AllCaregiverController.java.
Referenced by controller.AllCaregiverController.doUpdate(), controller.AllCaregiverController.handleAdd(), controller.AllCaregiverController.handleBlockRow(), controller.AllCaregiverController.handleDeleteRow(), controller.AllCaregiverController.initialize(), and controller.AllCaregiverController.readAllAndShowInTableView().
tableView
TableView<Caregiver> controller.AllCaregiverController.tableView private
Definition at line 28 of file AllCaregiverController.java.
tableviewContent
ObservableList<Caregiver> controller.AllCaregiverController.tableviewContent = FXCollections.observableArrayList() private
Definition at line 49 of file AllCaregiverController.java.
txfFirstname
TextField controller.AllCaregiverController.txfFirstname package
Definition at line 45 of file AllCaregiverController.java.
txfSurname
TextField controller.AllCaregiverController.txfSurname package
Definition at line 43 of file AllCaregiverController.java.
txfTelephone
TextField controller.AllCaregiverController.txfTelephone package
Definition at line 47 of file AllCaregiverController.java.
The documentation for this class was generated from the following file:
src/main/java/controller/AllCaregiverController.java