Nursing home student: model.Patient Class Reference
model.Patient Class Reference
Public Member Functions
Patient (String firstName, String surname, LocalDate dateOfBirth, String careLevel, String roomnumber, boolean shown)
Patient (long pid, String firstName, String surname, LocalDate dateOfBirth, String careLevel, String roomnumber, boolean shown)
long getPid ()
String getDateOfBirth ()
void setDateOfBirth (String dateOfBirth)
String getCareLevel ()
void setCareLevel (String careLevel)
String getRoomnumber ()
void setRoomnumber (String roomnumber)
boolean Shown ()
void setShown (boolean shown)
boolean add (Treatment m)
String toString ()
Public Member Functions inherited from model.Person
Person (String firstName, String surname)
String getFirstName ()
void setFirstName (String firstName)
String getSurname ()
void setSurname (String surname)
Private Attributes
long pid
LocalDate dateOfBirth
String careLevel
String roomnumber
boolean shown
List< Treatment > allTreatments = new ArrayList<Treatment>()
Detailed Description
Patients live in a NURSING home and are treated by nurses.
Definition at line 11 of file Patient.java.
Constructor & Destructor Documentation
Patient() [1/2]
model.Patient.Patient (String firstName, String surname, LocalDate dateOfBirth, String careLevel, String roomnumber, boolean shown)
constructs a patient from the given params.
Parameters
firstName
surname
dateOfBirth
careLevel
roomnumber
Definition at line 27 of file Patient.java.
{
        super(firstName, surname);
        this.dateOfBirth = dateOfBirth;
        this.careLevel = careLevel;
        this.roomnumber = roomnumber;
        this.shown = shown;
    }
References model.Patient.careLevel, model.Patient.dateOfBirth, model.Person.firstName, model.Patient.roomnumber, model.Patient.shown, and model.Person.surname.
Patient() [2/2]
model.Patient.Patient (long pid, String firstName, String surname, LocalDate dateOfBirth, String careLevel, String roomnumber, boolean shown)
constructs a patient from the given params.
Parameters
pid
firstName
surname
dateOfBirth
careLevel
roomnumber
Definition at line 44 of file Patient.java.
{
        super(firstName, surname);
        this.pid = pid;
        this.dateOfBirth = dateOfBirth;
        this.careLevel = careLevel;
        this.roomnumber = roomnumber;
        this.shown = shown;
    }
References model.Patient.careLevel, model.Patient.dateOfBirth, model.Person.firstName, model.Patient.pid, model.Patient.roomnumber, model.Patient.shown, and model.Person.surname.
Member Function Documentation
add()
boolean model.Patient.add (Treatment m)
adds a treatment to the treatment-list, if it does not already contain it.
Parameters
m Treatment
Returns
true if the treatment was not already part of the list. otherwise false
Definition at line 123 of file Patient.java.
{
        if (!this.allTreatments.contains(m)) {
            this.allTreatments.add(m);
            return true;
        }
        return false;
    }
getCareLevel()
String model.Patient.getCareLevel ()
Returns
careLevel
Definition at line 82 of file Patient.java.
{
        return careLevel;
    }
References model.Patient.careLevel.
Referenced by datastorage.PatientDAO.getCreateStatementString(), datastorage.PatientDAO.getUpdateStatementString(), and controller.TreatmentController.showData().
getDateOfBirth()
String model.Patient.getDateOfBirth ()
Returns
date of birth as a string
Definition at line 65 of file Patient.java.
{
        return dateOfBirth.toString();
    }
References model.Patient.dateOfBirth.
Referenced by datastorage.PatientDAO.getCreateStatementString(), and datastorage.PatientDAO.getUpdateStatementString().
getPid()
long model.Patient.getPid ()
Returns
patient id
Definition at line 57 of file Patient.java.
{
        return pid;
    }
References model.Patient.pid.
Referenced by datastorage.PatientDAO.getUpdateStatementString(), controller.NewTreatmentController.handleAdd(), controller.AllPatientController.handleBlockRow(), controller.AllTreatmentController.handleComboBox(), and controller.AllPatientController.handleDeleteRow().
getRoomnumber()
String model.Patient.getRoomnumber ()
Returns
roomNumber as string
Definition at line 98 of file Patient.java.
{
        return roomnumber;
    }
References model.Patient.roomnumber.
Referenced by datastorage.PatientDAO.getCreateStatementString(), and datastorage.PatientDAO.getUpdateStatementString().
setCareLevel()
void model.Patient.setCareLevel (String careLevel)
Parameters
careLevel new care level
Definition at line 90 of file Patient.java.
{
        this.careLevel = careLevel;
    }
References model.Patient.careLevel.
setDateOfBirth()
void model.Patient.setDateOfBirth (String dateOfBirth)
convert given param to a localDate and store as new birthOfDate
Parameters
dateOfBirth as string in the following format: YYYY-MM-DD
Definition at line 73 of file Patient.java.
{
        LocalDate birthday = DateConverter.convertStringToLocalDate(dateOfBirth);
        this.dateOfBirth = birthday;
    }
References utils.DateConverter.convertStringToLocalDate(), and model.Patient.dateOfBirth.
setRoomnumber()
void model.Patient.setRoomnumber (String roomnumber)
Parameters
roomnumber
Definition at line 106 of file Patient.java.
{
        this.roomnumber = roomnumber;
    }
References model.Patient.roomnumber.
setShown()
void model.Patient.setShown (boolean shown)
Definition at line 114 of file Patient.java.
{
        this.shown = shown;
    }
References model.Patient.shown.
Referenced by controller.AllPatientController.handleBlockRow().
Shown()
boolean model.Patient.Shown ()
Definition at line 110 of file Patient.java.
{
        return shown;
    }
References model.Patient.shown.
Referenced by datastorage.PatientDAO.getUpdateStatementString().
toString()
String model.Patient.toString ()
Returns
string-representation of the patient
Definition at line 135 of file Patient.java.
{
        return "Patient" + "\nMNID: " + this.pid +
                "\nFirstname: " + this.getFirstName() +
                "\nSurname: " + this.getSurname() +
                "\nBirthday: " + this.dateOfBirth +
                "\nCarelevel: " + this.careLevel +
                "\nRoomnumber: " + this.roomnumber +
                "\n";
    }
References model.Person.getFirstName(), and model.Person.getSurname().
Member Data Documentation
allTreatments
List<Treatment> model.Patient.allTreatments = new ArrayList<Treatment>() private
Definition at line 17 of file Patient.java.
careLevel
String model.Patient.careLevel private
Definition at line 14 of file Patient.java.
Referenced by model.Patient.getCareLevel(), model.Patient.Patient(), and model.Patient.setCareLevel().
dateOfBirth
LocalDate model.Patient.dateOfBirth private
Definition at line 13 of file Patient.java.
Referenced by model.Patient.getDateOfBirth(), model.Patient.Patient(), and model.Patient.setDateOfBirth().
pid
long model.Patient.pid private
Definition at line 12 of file Patient.java.
Referenced by model.Patient.getPid(), and model.Patient.Patient().
roomnumber
String model.Patient.roomnumber private
Definition at line 15 of file Patient.java.
Referenced by model.Patient.getRoomnumber(), model.Patient.Patient(), and model.Patient.setRoomnumber().
shown
boolean model.Patient.shown private
Definition at line 16 of file Patient.java.
Referenced by model.Patient.Patient(), model.Patient.setShown(), and model.Patient.Shown().
The documentation for this class was generated from the following file:
src/main/java/model/Patient.java