Nursing home student: controller.Main Class Reference
controller.Main Class Reference
Inherits Application.
Public Member Functions
void start (Stage primaryStage)
void mainWindow ()
Static Public Member Functions
static void main (String[] args)
Private Attributes
Stage primaryStage
Detailed Description
Definition at line 15 of file Main.java.
Member Function Documentation
main()
static void controller.Main.main (String[] args) static
Definition at line 57 of file Main.java.
{
        launch(args);
    }
mainWindow()
void controller.Main.mainWindow ()
loads LoginWindowView and sets it as the current scene.
Definition at line 32 of file Main.java.
{
        try {
            FXMLLoader loader = new FXMLLoader(Main.class.getResource("/LoginWindowView.fxml"));
            BorderPane pane = loader.load();
            Scene scene = new Scene(pane);
            this.primaryStage.setTitle("NHPlus");
            this.primaryStage.setScene(scene);
            this.primaryStage.setResizable(false);
            this.primaryStage.show();
            this.primaryStage.setOnCloseRequest(new EventHandler<WindowEvent>() {
                @Override
                public void handle(WindowEvent e) {
                    ConnectionBuilder.closeConnection();
                    Platform.exit();
                    System.exit(0);
                }
            });
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
References datastorage.ConnectionBuilder.closeConnection().
Referenced by controller.Main.start().
start()
void controller.Main.start (Stage primaryStage)
starts the application, sets the primaryStage and class the mainWindow method
Parameters
primaryStage primaryStage which sets the primaryStage in the class
Definition at line 24 of file Main.java.
{
        this.primaryStage = primaryStage;
        mainWindow();
    }
References controller.Main.mainWindow(), and controller.Main.primaryStage.
Member Data Documentation
primaryStage
Stage controller.Main.primaryStage private
Definition at line 17 of file Main.java.
Referenced by controller.Main.start().
The documentation for this class was generated from the following file:
src/main/java/controller/Main.java