Nursing home student: utils.DateConverter Class Reference
utils.DateConverter Class Reference
Static Public Member Functions
static LocalDate convertStringToLocalDate (String date)
static LocalTime convertStringToLocalTime (String time)
Detailed Description
Definition at line 6 of file DateConverter.java.
Member Function Documentation
convertStringToLocalDate()
static LocalDate utils.DateConverter.convertStringToLocalDate (String date) static
Definition at line 7 of file DateConverter.java.
{
        String[] array = date.split("-");
        LocalDate result = LocalDate.of(Integer.parseInt(array[0]), Integer.parseInt(array[1]),
                Integer.parseInt(array[2]));
        return result;
    }
Referenced by datastorage.PatientDAO.getInstanceFromResultSet(), datastorage.TreatmentDAO.getInstanceFromResultSet(), datastorage.PatientDAO.getListFromResultSet(), datastorage.TreatmentDAO.getListFromResultSet(), controller.AllPatientController.handleAdd(), model.Treatment.setDate(), model.Patient.setDateOfBirth(), and controller.TreatmentController.showData().
convertStringToLocalTime()
static LocalTime utils.DateConverter.convertStringToLocalTime (String time) static
Definition at line 14 of file DateConverter.java.
{
        String[] array = time.split(":");
        LocalTime result = LocalTime.of(Integer.parseInt(array[0]), Integer.parseInt(array[1]));
        return result;
    }
Referenced by datastorage.TreatmentDAO.getInstanceFromResultSet(), datastorage.TreatmentDAO.getListFromResultSet(), controller.NewTreatmentController.handleAdd(), model.Treatment.setBegin(), and model.Treatment.setEnd().
The documentation for this class was generated from the following file:
src/main/java/utils/DateConverter.java