Nursing home student: controller.TreatmentController Class Reference
controller.TreatmentController Class Reference
Public Member Functions
void initializeController (AllTreatmentController controller, Stage stage, Treatment treatment)
void handleChange ()
void handleCancel ()
Private Member Functions
void showData ()
void doUpdate ()
Private Attributes
Label lblPatientName
Label lblCaregiverName
Label lblCarelevel
TextField txtBegin
TextField txtEnd
TextField txtDescription
TextArea taRemarks
DatePicker datepicker
Button btnChange
Button btnCancel
AllTreatmentController controller
Stage stage
Patient patient
Caregiver caregiver
Treatment treatment
Detailed Description
The TreatmentController contains the entire logic of the treatment view. It determines which data is displayed and how to react to events.
Definition at line 20 of file TreatmentController.java.
Member Function Documentation
doUpdate()
void controller.TreatmentController.doUpdate () private
Calls the update method in the TreatmentDAO, with the new treatment data
Definition at line 103 of file TreatmentController.java.
{
        TreatmentDAO dao = DAOFactory.getDAOFactory().createTreatmentDAO();
        try {
            dao.update(treatment);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.DAOFactory.createTreatmentDAO(), datastorage.DAOFactory.getDAOFactory(), controller.TreatmentController.treatment, and datastorage.DAOimp< T >.update().
Referenced by controller.TreatmentController.handleChange().
handleCancel()
void controller.TreatmentController.handleCancel ()
closes window
Definition at line 116 of file TreatmentController.java.
{
        stage.close();
    }
References controller.TreatmentController.stage.
handleChange()
void controller.TreatmentController.handleChange ()
handle changes made in the treatment fields, calls the doUpdate method, calls the readAllAndShowInTableView in the AllTreatmentController and closes the window
Definition at line 89 of file TreatmentController.java.
{
        this.treatment.setDate(this.datepicker.getValue().toString());
        this.treatment.setBegin(txtBegin.getText());
        this.treatment.setEnd(txtEnd.getText());
        this.treatment.setDescription(txtDescription.getText());
        this.treatment.setRemarks(taRemarks.getText());
        doUpdate();
        controller.readAllAndShowInTableView();
        stage.close();
    }
References controller.TreatmentController.doUpdate(), model.Treatment.setBegin(), model.Treatment.setDate(), model.Treatment.setDescription(), model.Treatment.setEnd(), model.Treatment.setRemarks(), controller.TreatmentController.stage, controller.TreatmentController.taRemarks, controller.TreatmentController.txtBegin, controller.TreatmentController.txtDescription, and controller.TreatmentController.txtEnd.
initializeController()
void controller.TreatmentController.initializeController (AllTreatmentController controller, Stage stage, Treatment treatment)
Initializes the corresponding fields. Is called as soon as the corresponding FXML file is to be displayed.
Parameters
controller saves the controller of the original AllTreatmentController to later display the changes there
stage the stage initialized in the AllTreatmentController
treatment treatment, which needs to be displayed
Definition at line 54 of file TreatmentController.java.
{
        this.stage = stage;
        this.controller= controller;
        PatientDAO pDao = DAOFactory.getDAOFactory().createPatientDAO();
        CaregiverDAO cDao = DAOFactory.getDAOFactory().createCaregiverDAO();
        try {
            this.patient = pDao.read((int) treatment.getPid());
            this.caregiver = cDao.read((int) treatment.getCid());
            this.treatment = treatment;
            showData();
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References controller.TreatmentController.controller, datastorage.DAOFactory.createCaregiverDAO(), datastorage.DAOFactory.createPatientDAO(), model.Treatment.getCid(), datastorage.DAOFactory.getDAOFactory(), model.Treatment.getPid(), datastorage.DAOimp< T >.read(), controller.TreatmentController.showData(), controller.TreatmentController.stage, and controller.TreatmentController.treatment.
showData()
void controller.TreatmentController.showData () private
displays full name of the patient and caregiver and full data of the treatment
Definition at line 72 of file TreatmentController.java.
{
        this.lblPatientName.setText(patient.getSurname()+", "+patient.getFirstName());
        this.lblCaregiverName.setText(caregiver.getSurname()+", "+caregiver.getFirstName());
        this.lblCarelevel.setText(patient.getCareLevel());
        LocalDate date = DateConverter.convertStringToLocalDate(treatment.getDate());
        this.datepicker.setValue(date);
        this.txtBegin.setText(this.treatment.getBegin());
        this.txtEnd.setText(this.treatment.getEnd());
        this.txtDescription.setText(this.treatment.getDescription());
        this.taRemarks.setText(this.treatment.getRemarks());
    }
References controller.TreatmentController.caregiver, utils.DateConverter.convertStringToLocalDate(), model.Treatment.getBegin(), model.Patient.getCareLevel(), model.Treatment.getDate(), model.Treatment.getDescription(), model.Treatment.getEnd(), model.Person.getFirstName(), model.Treatment.getRemarks(), model.Person.getSurname(), controller.TreatmentController.patient, and controller.TreatmentController.treatment.
Referenced by controller.TreatmentController.initializeController().
Member Data Documentation
btnCancel
Button controller.TreatmentController.btnCancel private
Definition at line 40 of file TreatmentController.java.
btnChange
Button controller.TreatmentController.btnChange private
Definition at line 38 of file TreatmentController.java.
caregiver
Caregiver controller.TreatmentController.caregiver private
Definition at line 45 of file TreatmentController.java.
Referenced by controller.TreatmentController.showData().
controller
AllTreatmentController controller.TreatmentController.controller private
Definition at line 42 of file TreatmentController.java.
Referenced by controller.TreatmentController.initializeController().
datepicker
DatePicker controller.TreatmentController.datepicker private
Definition at line 36 of file TreatmentController.java.
lblCaregiverName
Label controller.TreatmentController.lblCaregiverName private
Definition at line 24 of file TreatmentController.java.
lblCarelevel
Label controller.TreatmentController.lblCarelevel private
Definition at line 26 of file TreatmentController.java.
lblPatientName
Label controller.TreatmentController.lblPatientName private
Definition at line 22 of file TreatmentController.java.
patient
Patient controller.TreatmentController.patient private
Definition at line 44 of file TreatmentController.java.
Referenced by controller.TreatmentController.showData().
stage
Stage controller.TreatmentController.stage private
Definition at line 43 of file TreatmentController.java.
Referenced by controller.TreatmentController.handleCancel(), controller.TreatmentController.handleChange(), and controller.TreatmentController.initializeController().
taRemarks
TextArea controller.TreatmentController.taRemarks private
Definition at line 34 of file TreatmentController.java.
Referenced by controller.TreatmentController.handleChange().
treatment
Treatment controller.TreatmentController.treatment private
Definition at line 46 of file TreatmentController.java.
Referenced by controller.TreatmentController.doUpdate(), controller.TreatmentController.initializeController(), and controller.TreatmentController.showData().
txtBegin
TextField controller.TreatmentController.txtBegin private
Definition at line 28 of file TreatmentController.java.
Referenced by controller.TreatmentController.handleChange().
txtDescription
TextField controller.TreatmentController.txtDescription private
Definition at line 32 of file TreatmentController.java.
Referenced by controller.TreatmentController.handleChange().
txtEnd
TextField controller.TreatmentController.txtEnd private
Definition at line 30 of file TreatmentController.java.
Referenced by controller.TreatmentController.handleChange().
The documentation for this class was generated from the following file:
src/main/java/controller/TreatmentController.java