Nursing home student: datastorage.ConnectionBuilder Class Reference
datastorage.ConnectionBuilder Class Reference
Static Public Member Functions
static Connection getConnection ()
static void closeConnection ()
Private Member Functions
ConnectionBuilder ()
Static Private Attributes
static Connection conn
Detailed Description
creates a connection between the front-end and the back-end.
Definition at line 10 of file ConnectionBuilder.java.
Constructor & Destructor Documentation
ConnectionBuilder()
datastorage.ConnectionBuilder.ConnectionBuilder () private
creates connection to back-end
Definition at line 17 of file ConnectionBuilder.java.
{
        try {
            Class.forName("org.hsqldb.jdbc.JDBCDriver");
            System.out.println("Working Directory = " + System.getProperty("user.dir"));
            conn = DriverManager.getConnection("jdbc:hsqldb:db/nursingHomeDB;shutdown=true;user=SA;password=SA");
        } catch (ClassNotFoundException e) {
            e.printStackTrace();
            System.out.println("Treiberklasse konnte nicht gefunden werden!");
        } catch (SQLException e) {
            System.out.println("Verbindung zur Datenbank konnte nicht aufgebaut werden!");
            e.printStackTrace();
        }
    }
References datastorage.ConnectionBuilder.conn.
Referenced by datastorage.ConnectionBuilder.getConnection().
Member Function Documentation
closeConnection()
static void datastorage.ConnectionBuilder.closeConnection () static
closes connection to application
Definition at line 46 of file ConnectionBuilder.java.
{
        try {
            if(conn != null){
                conn.close();
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.ConnectionBuilder.conn.
Referenced by controller.Main.mainWindow().
getConnection()
static Connection datastorage.ConnectionBuilder.getConnection () static
when no Connection has been made, initializes a new ConnectionBuilder
Returns
Connection
Definition at line 36 of file ConnectionBuilder.java.
{
        if (conn == null) {
            new ConnectionBuilder();
        }
        return conn;
    }
References datastorage.ConnectionBuilder.conn, and datastorage.ConnectionBuilder.ConnectionBuilder().
Referenced by datastorage.DAOFactory.createCaregiverDAO(), datastorage.DAOFactory.createPatientDAO(), datastorage.DAOFactory.createTreatmentDAO(), and account.UserManager.getInstance().
Member Data Documentation
conn
Connection datastorage.ConnectionBuilder.conn static private
Definition at line 11 of file ConnectionBuilder.java.
Referenced by datastorage.ConnectionBuilder.closeConnection(), datastorage.ConnectionBuilder.ConnectionBuilder(), and datastorage.ConnectionBuilder.getConnection().
The documentation for this class was generated from the following file:
src/main/java/datastorage/ConnectionBuilder.java