Nursing home student: controller.NewTreatmentController Class Reference
controller.NewTreatmentController Class Reference
Public Member Functions
void initialize (AllTreatmentController controller, Stage stage, Patient patient)
void handleAdd ()
void handleCancel ()
Private Member Functions
void showPatientData ()
void createComboBoxDataCaregiver ()
Caregiver searchInListCaregiver (String surname)
void createTreatment (Treatment treatment)
Private Attributes
TableView< Treatment > tableView
Label lblSurname
Label lblFirstname
TextField txtBegin
TextField txtEnd
TextField txtDescription
TextArea taRemarks
DatePicker datepicker
ComboBox< String > comboBox
ObservableList< Treatment > tableviewContent
TreatmentDAO dao
ObservableList< String > myComboBoxData
ArrayList< Caregiver > caregiverList
AllTreatmentController controller
Patient patient
Stage stage
Detailed Description
The NewTreatmentController contains the entire logic of the new treatment view. It determines which data is displayed and how to react to events.
Definition at line 24 of file NewTreatmentController.java.
Member Function Documentation
createComboBoxDataCaregiver()
void controller.NewTreatmentController.createComboBoxDataCaregiver () private
Sets Data that will be show when clicked on ComboBox.
Definition at line 77 of file NewTreatmentController.java.
{
        CaregiverDAO dao = DAOFactory.getDAOFactory().createCaregiverDAO();
        try {
            caregiverList = (ArrayList<Caregiver>) dao.readAll();
            for (Caregiver caregiver: caregiverList) {
                this.myComboBoxData.add(caregiver.getSurname());
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
References controller.NewTreatmentController.caregiverList, datastorage.DAOFactory.createCaregiverDAO(), controller.NewTreatmentController.dao, datastorage.DAOFactory.getDAOFactory(), and datastorage.DAOimp< T >.readAll().
Referenced by controller.NewTreatmentController.initialize().
createTreatment()
void controller.NewTreatmentController.createTreatment (Treatment treatment) private
Creates a treatment and calls the create method in the TreatmentDAO
Parameters
treatment treatment which will be created in the dao
Definition at line 142 of file NewTreatmentController.java.
{
        TreatmentDAO dao = DAOFactory.getDAOFactory().createTreatmentDAO();
        try {
            dao.create(treatment);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.DAOimp< T >.create(), datastorage.DAOFactory.createTreatmentDAO(), controller.NewTreatmentController.dao, and datastorage.DAOFactory.getDAOFactory().
Referenced by controller.NewTreatmentController.handleAdd().
handleAdd()
void controller.NewTreatmentController.handleAdd ()
handles an add-click-event. Takes in necessary data and calls createTreatment method
Definition at line 108 of file NewTreatmentController.java.
{
        LocalDate date = this.datepicker.getValue();
        String s_begin = txtBegin.getText();
        LocalTime begin = DateConverter.convertStringToLocalTime(txtBegin.getText());
        LocalTime end = DateConverter.convertStringToLocalTime(txtEnd.getText());
        String description = txtDescription.getText();
        String remarks = taRemarks.getText();
        if(description.equals("")) {
            return;
        }
        try{
            String c = this.comboBox.getSelectionModel().getSelectedItem();
            Caregiver caregiver = searchInListCaregiver(c);
            Treatment treatment = new Treatment(patient.getPid(), caregiver.getId(), date,
                    begin, end, description, remarks, true);
            createTreatment(treatment);
            controller.readAllAndShowInTableView();
            stage.close();
        }
        catch(NullPointerException e){
            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setTitle("Information");
            alert.setHeaderText("Pfleger für die Behandlung fehlt!");
            alert.setContentText("Wählen Sie über die Combobox einen Pfleger aus!");
            alert.showAndWait();
        }
    }
References utils.DateConverter.convertStringToLocalTime(), controller.NewTreatmentController.createTreatment(), model.Caregiver.getId(), model.Patient.getPid(), controller.NewTreatmentController.patient, controller.NewTreatmentController.searchInListCaregiver(), controller.NewTreatmentController.stage, controller.NewTreatmentController.taRemarks, controller.NewTreatmentController.txtBegin, controller.NewTreatmentController.txtDescription, and controller.NewTreatmentController.txtEnd.
handleCancel()
void controller.NewTreatmentController.handleCancel ()
handles a cancel-click-event. Closes the window
Definition at line 155 of file NewTreatmentController.java.
{
        stage.close();
    }
References controller.NewTreatmentController.stage.
initialize()
void controller.NewTreatmentController.initialize (AllTreatmentController controller, Stage stage, Patient patient)
Initializes the corresponding fields. Is called when clicked on btnNewTreatment.
Definition at line 57 of file NewTreatmentController.java.
{
        this.controller= controller;
        this.patient = patient;
        this.stage = stage;
        comboBox.setItems(myComboBoxData);
        createComboBoxDataCaregiver();
        showPatientData();
    }
References controller.NewTreatmentController.comboBox, controller.NewTreatmentController.controller, controller.NewTreatmentController.createComboBoxDataCaregiver(), controller.NewTreatmentController.myComboBoxData, controller.NewTreatmentController.patient, controller.NewTreatmentController.showPatientData(), and controller.NewTreatmentController.stage.
searchInListCaregiver()
Caregiver controller.NewTreatmentController.searchInListCaregiver (String surname) private
Goes through List of all Caregivers.
Parameters
surname String which all caregivers will be evaluated with
Returns
caregiver with the corresponding surname.
Definition at line 95 of file NewTreatmentController.java.
{
        for (int i =0; i<this.caregiverList.size();i++){
            if(this.caregiverList.get(i).getSurname().equals(surname)){
                return this.caregiverList.get(i);
            }
        }
        return null;
    }
Referenced by controller.NewTreatmentController.handleAdd().
showPatientData()
void controller.NewTreatmentController.showPatientData () private
Sets full name of the Patient, to be shown in the new Window.
Definition at line 69 of file NewTreatmentController.java.
{
        this.lblFirstname.setText(patient.getFirstName());
        this.lblSurname.setText(patient.getSurname());
    }
References model.Person.getFirstName(), model.Person.getSurname(), and controller.NewTreatmentController.patient.
Referenced by controller.NewTreatmentController.initialize().
Member Data Documentation
caregiverList
ArrayList<Caregiver> controller.NewTreatmentController.caregiverList private
Definition at line 49 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.createComboBoxDataCaregiver().
comboBox
ComboBox<String> controller.NewTreatmentController.comboBox private
Definition at line 42 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.initialize().
controller
AllTreatmentController controller.NewTreatmentController.controller private
Definition at line 50 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.initialize().
dao
TreatmentDAO controller.NewTreatmentController.dao private
Definition at line 46 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.createComboBoxDataCaregiver(), and controller.NewTreatmentController.createTreatment().
datepicker
DatePicker controller.NewTreatmentController.datepicker private
Definition at line 40 of file NewTreatmentController.java.
lblFirstname
Label controller.NewTreatmentController.lblFirstname private
Definition at line 30 of file NewTreatmentController.java.
lblSurname
Label controller.NewTreatmentController.lblSurname private
Definition at line 28 of file NewTreatmentController.java.
myComboBoxData
ObservableList<String> controller.NewTreatmentController.myComboBoxData private
Initial value:
=
            FXCollections.observableArrayList()
Definition at line 47 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.initialize().
patient
Patient controller.NewTreatmentController.patient private
Definition at line 51 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.handleAdd(), controller.NewTreatmentController.initialize(), and controller.NewTreatmentController.showPatientData().
stage
Stage controller.NewTreatmentController.stage private
Definition at line 52 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.handleAdd(), controller.NewTreatmentController.handleCancel(), and controller.NewTreatmentController.initialize().
tableView
TableView<Treatment> controller.NewTreatmentController.tableView private
Definition at line 26 of file NewTreatmentController.java.
tableviewContent
ObservableList<Treatment> controller.NewTreatmentController.tableviewContent private
Initial value:
=
            FXCollections.observableArrayList()
Definition at line 44 of file NewTreatmentController.java.
taRemarks
TextArea controller.NewTreatmentController.taRemarks private
Definition at line 38 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.handleAdd().
txtBegin
TextField controller.NewTreatmentController.txtBegin private
Definition at line 32 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.handleAdd().
txtDescription
TextField controller.NewTreatmentController.txtDescription private
Definition at line 36 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.handleAdd().
txtEnd
TextField controller.NewTreatmentController.txtEnd private
Definition at line 34 of file NewTreatmentController.java.
Referenced by controller.NewTreatmentController.handleAdd().
The documentation for this class was generated from the following file:
src/main/java/controller/NewTreatmentController.java