Nursing home student: controller.AllTreatmentController Class Reference
controller.AllTreatmentController Class Reference
Public Member Functions
void initialize ()
void readAllAndShowInTableView ()
void handleComboBox ()
void handleDelete ()
void handleNewTreatment ()
void handleMouseClick ()
void newTreatmentWindow (Patient patient)
void treatmentWindow (Treatment treatment)
void handleBlockRow ()
Private Member Functions
void createComboBoxDataPatient ()
Patient searchInListPatient (String surname)
Private Attributes
TableView< Treatment > tableView
TableColumn< Treatment, Integer > colID
TableColumn< Treatment, Integer > colPid
TableColumn< Treatment, Integer > colCid
TableColumn< Treatment, String > colDate
TableColumn< Treatment, String > colBegin
TableColumn< Treatment, String > colEnd
TableColumn< Treatment, String > colDescription
ComboBox< String > comboBox
Button btnNewTreatment
Button btnDelete
ObservableList< Treatment > tableviewContent
TreatmentDAO dao
ObservableList< String > myComboBoxData
ArrayList< Patient > patientList
ArrayList< Caregiver > caregiverList
Main main
Detailed Description
The AllTreatmentController contains the entire logic of the all treatment view. It determines which data is displayed and how to react to events.
Definition at line 28 of file AllTreatmentController.java.
Member Function Documentation
createComboBoxDataPatient()
void controller.AllTreatmentController.createComboBoxDataPatient () private
Sets Data that will be show when clicked on ComboBox. Does not show treatments from blocked patients.
Definition at line 111 of file AllTreatmentController.java.
{
        PatientDAO dao = DAOFactory.getDAOFactory().createPatientDAO();
        try {
            patientList = (ArrayList<Patient>) dao.readAllUnblocked();
            this.myComboBoxData.add("alle");
            for (Patient patient: patientList) {
                this.myComboBoxData.add(patient.getSurname());
            }
        }catch(SQLException e){
            e.printStackTrace();
        }
    }
References datastorage.DAOFactory.createPatientDAO(), controller.AllTreatmentController.dao, datastorage.DAOFactory.getDAOFactory(), controller.AllTreatmentController.patientList, and datastorage.DAOimp< T >.readAllUnblocked().
Referenced by controller.AllTreatmentController.initialize().
handleBlockRow()
void controller.AllTreatmentController.handleBlockRow ()
handles a block-click-event. Changes the shown variable of the patient in the database to indicate if this caregiver should be shown
Definition at line 275 of file AllTreatmentController.java.
{
        Treatment selectedItem = this.tableView.getSelectionModel().getSelectedItem();
        try {
            selectedItem.setShown(false);
            dao.update(selectedItem);
            this.tableView.getItems().remove(selectedItem);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References controller.AllTreatmentController.dao, model.Treatment.setShown(), and datastorage.DAOimp< T >.update().
handleComboBox()
void controller.AllTreatmentController.handleComboBox ()
handles which treatments will be shown according to the selected patient
Definition at line 129 of file AllTreatmentController.java.
{
        String p = this.comboBox.getSelectionModel().getSelectedItem();
        this.tableviewContent.clear();
        this.dao = DAOFactory.getDAOFactory().createTreatmentDAO();
        List<Treatment> allTreatments;
        if(p.equals("alle")){
            try {
                allTreatments= this.dao.readAll();
                for (Treatment treatment : allTreatments) {
                    this.tableviewContent.add(treatment);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
        Patient patient = searchInListPatient(p);
        if(patient !=null){
            try {
                allTreatments = dao.readTreatmentsByPid(patient.getPid());
                for (Treatment treatment : allTreatments) {
                    this.tableviewContent.add(treatment);
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
References datastorage.DAOFactory.createTreatmentDAO(), controller.AllTreatmentController.dao, datastorage.DAOFactory.getDAOFactory(), model.Patient.getPid(), datastorage.DAOimp< T >.readAll(), datastorage.TreatmentDAO.readTreatmentsByPid(), and controller.AllTreatmentController.searchInListPatient().
handleDelete()
void controller.AllTreatmentController.handleDelete ()
handles a delete-click-event. Calls the delete methods in the TreatmentDAO
Definition at line 175 of file AllTreatmentController.java.
{
        int index = this.tableView.getSelectionModel().getSelectedIndex();
        Treatment t = this.tableviewContent.remove(index);
        TreatmentDAO dao = DAOFactory.getDAOFactory().createTreatmentDAO();
        try {
            dao.deleteById(t.getTid());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.DAOFactory.createTreatmentDAO(), controller.AllTreatmentController.dao, datastorage.DAOimp< T >.deleteById(), datastorage.DAOFactory.getDAOFactory(), and model.Treatment.getTid().
handleMouseClick()
void controller.AllTreatmentController.handleMouseClick ()
handles double mouse-click-event on treatments. Calls method treatmentWindow with clicked treatment
Definition at line 210 of file AllTreatmentController.java.
{
        tableView.setOnMouseClicked(event -> {
            if (event.getClickCount() == 2 && (tableView.getSelectionModel().getSelectedItem() != null)) {
                int index = this.tableView.getSelectionModel().getSelectedIndex();
                Treatment treatment = this.tableviewContent.get(index);
                treatmentWindow(treatment);
            }
        });
    }
References controller.AllTreatmentController.tableView.
handleNewTreatment()
void controller.AllTreatmentController.handleNewTreatment ()
handles a new-treatment-click-event. Saves selected patient and calls the create newTreatmentWindow method with the selected patient
Definition at line 191 of file AllTreatmentController.java.
{
        try{
            String p = this.comboBox.getSelectionModel().getSelectedItem();
            Patient patient = searchInListPatient(p);
            newTreatmentWindow(patient);
        }
        catch(NullPointerException e){
            Alert alert = new Alert(Alert.AlertType.INFORMATION);
            alert.setTitle("Information");
            alert.setHeaderText("Patient für die Behandlung fehlt!");
            alert.setContentText("Wählen Sie über die Combobox einen Patienten aus!");
            alert.showAndWait();
        }
    }
References controller.AllTreatmentController.newTreatmentWindow(), and controller.AllTreatmentController.searchInListPatient().
initialize()
void controller.AllTreatmentController.initialize ()
Initializes the corresponding fields. Is called as soon as the corresponding FXML file is to be displayed.
Definition at line 65 of file AllTreatmentController.java.
{
        readAllAndShowInTableView();
        comboBox.setItems(myComboBoxData);
        comboBox.getSelectionModel().select(0);
        this.main = main;
        this.colID.setCellValueFactory(new PropertyValueFactory<Treatment, Integer>("tid"));
        this.colPid.setCellValueFactory(new PropertyValueFactory<Treatment, Integer>("pid"));
        this.colCid.setCellValueFactory(new PropertyValueFactory<Treatment, Integer>("cid"));
        this.colDate.setCellValueFactory(new PropertyValueFactory<Treatment, String>("date"));
        this.colBegin.setCellValueFactory(new PropertyValueFactory<Treatment, String>("begin"));
        this.colEnd.setCellValueFactory(new PropertyValueFactory<Treatment, String>("end"));
        this.colDescription.setCellValueFactory(new PropertyValueFactory<Treatment, String>("description"));
        this.tableView.setItems(this.tableviewContent);
        createComboBoxDataPatient();
        try {
            Statement statement = dao.getConn().createStatement();
            statement.executeQuery("DELETE FROM treatment WHERE show = FALSE AND blockeddate <= DATEADD('YEAR', -10, CURRENT_DATE);");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
References controller.AllTreatmentController.comboBox, controller.AllTreatmentController.createComboBoxDataPatient(), controller.AllTreatmentController.dao, datastorage.DAOimp< T >.getConn(), controller.AllTreatmentController.main, controller.AllTreatmentController.myComboBoxData, and controller.AllTreatmentController.readAllAndShowInTableView().
newTreatmentWindow()
void controller.AllTreatmentController.newTreatmentWindow (Patient patient)
loads NewTreatmentView and sets it as the current scene. Calls initialize in the NewTreatmentController
Parameters
patient patient which gets passed to the NewTreatmentController
Definition at line 226 of file AllTreatmentController.java.
{
        try {
            FXMLLoader loader = new FXMLLoader(Main.class.getResource("/NewTreatmentView.fxml"));
            AnchorPane pane = loader.load();
            Scene scene = new Scene(pane);
            //da die primaryStage noch im Hintergrund bleiben soll
            Stage stage = new Stage();
            NewTreatmentController controller = loader.getController();
            controller.initialize(this, stage, patient);
            stage.setScene(scene);
            stage.setResizable(false);
            stage.showAndWait();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
Referenced by controller.AllTreatmentController.handleNewTreatment().
readAllAndShowInTableView()
void controller.AllTreatmentController.readAllAndShowInTableView ()
calls readAll in TreatmentDAO and shows treatments in the table
Definition at line 92 of file AllTreatmentController.java.
{
        this.tableviewContent.clear();
        comboBox.getSelectionModel().select(0);
        this.dao = DAOFactory.getDAOFactory().createTreatmentDAO();
        List<Treatment> allTreatments;
        try {
            allTreatments = dao.readAllUnblocked();
            for (Treatment treatment : allTreatments) {
                this.tableviewContent.add(treatment);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References controller.AllTreatmentController.comboBox, datastorage.DAOFactory.createTreatmentDAO(), controller.AllTreatmentController.dao, datastorage.DAOFactory.getDAOFactory(), and datastorage.DAOimp< T >.readAllUnblocked().
Referenced by controller.AllTreatmentController.initialize().
searchInListPatient()
Patient controller.AllTreatmentController.searchInListPatient (String surname) private
Goes through List of all patients.
Parameters
surname String which all patients will be evaluated with
Returns
patient with the corresponding surname.
Definition at line 162 of file AllTreatmentController.java.
{
        for (int i =0; i<this.patientList.size();i++){
            if(this.patientList.get(i).getSurname().equals(surname)){
                return this.patientList.get(i);
            }
        }
        return null;
    }
Referenced by controller.AllTreatmentController.handleComboBox(), and controller.AllTreatmentController.handleNewTreatment().
treatmentWindow()
void controller.AllTreatmentController.treatmentWindow (Treatment treatment)
loads TreatmentView and sets it as the current scene. Calls initializeContoller in the TreatmentController
Parameters
treatment treatment which gets passed to the TreatmentController
Definition at line 251 of file AllTreatmentController.java.
{
        try {
            FXMLLoader loader = new FXMLLoader(Main.class.getResource("/TreatmentView.fxml"));
            AnchorPane pane = loader.load();
            Scene scene = new Scene(pane);
            //da die primaryStage noch im Hintergrund bleiben soll
            Stage stage = new Stage();
            TreatmentController controller = loader.getController();
            controller.initializeController(this, stage, treatment);
            stage.setScene(scene);
            stage.setResizable(false);
            stage.showAndWait();
        } catch (IOException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
    }
Member Data Documentation
btnDelete
Button controller.AllTreatmentController.btnDelete private
Definition at line 50 of file AllTreatmentController.java.
btnNewTreatment
Button controller.AllTreatmentController.btnNewTreatment private
Definition at line 48 of file AllTreatmentController.java.
caregiverList
ArrayList<Caregiver> controller.AllTreatmentController.caregiverList private
Definition at line 59 of file AllTreatmentController.java.
colBegin
TableColumn<Treatment, String> controller.AllTreatmentController.colBegin private
Definition at line 40 of file AllTreatmentController.java.
colCid
TableColumn<Treatment, Integer> controller.AllTreatmentController.colCid private
Definition at line 36 of file AllTreatmentController.java.
colDate
TableColumn<Treatment, String> controller.AllTreatmentController.colDate private
Definition at line 38 of file AllTreatmentController.java.
colDescription
TableColumn<Treatment, String> controller.AllTreatmentController.colDescription private
Definition at line 44 of file AllTreatmentController.java.
colEnd
TableColumn<Treatment, String> controller.AllTreatmentController.colEnd private
Definition at line 42 of file AllTreatmentController.java.
colID
TableColumn<Treatment, Integer> controller.AllTreatmentController.colID private
Definition at line 32 of file AllTreatmentController.java.
colPid
TableColumn<Treatment, Integer> controller.AllTreatmentController.colPid private
Definition at line 34 of file AllTreatmentController.java.
comboBox
ComboBox<String> controller.AllTreatmentController.comboBox private
Definition at line 46 of file AllTreatmentController.java.
Referenced by controller.AllTreatmentController.initialize(), and controller.AllTreatmentController.readAllAndShowInTableView().
dao
TreatmentDAO controller.AllTreatmentController.dao private
Definition at line 54 of file AllTreatmentController.java.
Referenced by controller.AllTreatmentController.createComboBoxDataPatient(), controller.AllTreatmentController.handleBlockRow(), controller.AllTreatmentController.handleComboBox(), controller.AllTreatmentController.handleDelete(), controller.AllTreatmentController.initialize(), and controller.AllTreatmentController.readAllAndShowInTableView().
main
Main controller.AllTreatmentController.main private
Definition at line 60 of file AllTreatmentController.java.
Referenced by controller.AllTreatmentController.initialize().
myComboBoxData
ObservableList<String> controller.AllTreatmentController.myComboBoxData private
Initial value:
=
            FXCollections.observableArrayList()
Definition at line 55 of file AllTreatmentController.java.
Referenced by controller.AllTreatmentController.initialize().
patientList
ArrayList<Patient> controller.AllTreatmentController.patientList private
Definition at line 57 of file AllTreatmentController.java.
Referenced by controller.AllTreatmentController.createComboBoxDataPatient().
tableView
TableView<Treatment> controller.AllTreatmentController.tableView private
Definition at line 30 of file AllTreatmentController.java.
Referenced by controller.AllTreatmentController.handleMouseClick().
tableviewContent
ObservableList<Treatment> controller.AllTreatmentController.tableviewContent private
Initial value:
=
            FXCollections.observableArrayList()
Definition at line 52 of file AllTreatmentController.java.
The documentation for this class was generated from the following file:
src/main/java/controller/AllTreatmentController.java