Nursing home student: datastorage.DAOimp< T > Class Template Reference
datastorage.DAOimp< T > Class Template Reference abstract
Public Member Functions
DAOimp (Connection conn)
void create (T t) throws SQLException
T read (long key) throws SQLException
List< T > readAll () throws SQLException
List< T > readAllUnblocked () throws SQLException
void update (T t) throws SQLException
void deleteById (long key) throws SQLException
Connection getConn ()
void create (T t) throws SQLException
T read (long key) throws SQLException
List< T > readAll () throws SQLException
List< T > readAllUnblocked () throws SQLException
void update (T t) throws SQLException
void deleteById (long key) throws SQLException
Protected Member Functions
abstract String getCreateStatementString (T t)
abstract String getReadByIDStatementString (long key)
abstract T getInstanceFromResultSet (ResultSet set) throws SQLException
abstract String getReadAllStatementString ()
abstract String getReadAllUnblockedStatementString ()
abstract ArrayList< T > getListFromResultSet (ResultSet set) throws SQLException
abstract String getUpdateStatementString (T t)
abstract String getDeleteStatementString (long key)
Protected Attributes
Connection conn
Detailed Description
Definition at line 10 of file DAOimp.java.
Constructor & Destructor Documentation
DAOimp()
datastorage.DAOimp< T >.DAOimp (Connection conn)
sets Connection
Parameters
conn
Definition at line 17 of file DAOimp.java.
{
        this.conn = conn;
    }
References datastorage.DAOimp< T >.conn.
Member Function Documentation
create()
void datastorage.DAOimp< T >.create (T t) throws SQLException
creates a new Statement of the given Object
Parameters
t
Exceptions
SQLException
Implements datastorage.DAO< T >.
Definition at line 27 of file DAOimp.java.
{
        Statement st = conn.createStatement();
        st.executeUpdate(getCreateStatementString(t));
    }
References datastorage.DAOimp< T >.conn, and datastorage.DAOimp< T >.getCreateStatementString().
Referenced by controller.NewTreatmentController.createTreatment(), controller.AllCaregiverController.handleAdd(), and controller.AllPatientController.handleAdd().
deleteById()
void datastorage.DAOimp< T >.deleteById (long key) throws SQLException
calls getDeleteStatementString method, with key
Parameters
key id of Object which gets deleted
Exceptions
SQLException
Implements datastorage.DAO< T >.
Definition at line 96 of file DAOimp.java.
{
        Statement st = conn.createStatement();
        st.executeUpdate(getDeleteStatementString(key));
    }
References datastorage.DAOimp< T >.conn, and datastorage.DAOimp< T >.getDeleteStatementString().
Referenced by controller.AllTreatmentController.handleDelete(), controller.AllCaregiverController.handleDeleteRow(), and controller.AllPatientController.handleDeleteRow().
getConn()
Connection datastorage.DAOimp< T >.getConn ()
Definition at line 117 of file DAOimp.java.
{
        return conn;
    }
References datastorage.DAOimp< T >.conn.
Referenced by controller.AllCaregiverController.initialize(), controller.AllPatientController.initialize(), and controller.AllTreatmentController.initialize().
getCreateStatementString()
abstract String datastorage.DAOimp< T >.getCreateStatementString (T t) abstract protected
Referenced by datastorage.DAOimp< T >.create().
getDeleteStatementString()
abstract String datastorage.DAOimp< T >.getDeleteStatementString (long key) abstract protected
Referenced by datastorage.DAOimp< T >.deleteById().
getInstanceFromResultSet()
abstract T datastorage.DAOimp< T >.getInstanceFromResultSet (ResultSet set) throws SQLException abstract protected
Referenced by datastorage.DAOimp< T >.read().
getListFromResultSet()
abstract ArrayList< T > datastorage.DAOimp< T >.getListFromResultSet (ResultSet set) throws SQLException abstract protected
Referenced by datastorage.DAOimp< T >.readAll(), and datastorage.DAOimp< T >.readAllUnblocked().
getReadAllStatementString()
abstract String datastorage.DAOimp< T >.getReadAllStatementString () abstract protected
Referenced by datastorage.DAOimp< T >.readAll().
getReadAllUnblockedStatementString()
abstract String datastorage.DAOimp< T >.getReadAllUnblockedStatementString () abstract protected
Referenced by datastorage.DAOimp< T >.readAllUnblocked().
getReadByIDStatementString()
abstract String datastorage.DAOimp< T >.getReadByIDStatementString (long key) abstract protected
Referenced by datastorage.DAOimp< T >.read().
getUpdateStatementString()
abstract String datastorage.DAOimp< T >.getUpdateStatementString (T t) abstract protected
Referenced by datastorage.DAOimp< T >.update().
read()
T datastorage.DAOimp< T >.read (long key) throws SQLException
calls getReadByIDStatementString method and makes a new object out of the result
Parameters
key id after which is being evaluated
Returns
found object
Exceptions
SQLException
Implements datastorage.DAO< T >.
Definition at line 39 of file DAOimp.java.
{
        T object = null;
        Statement st = conn.createStatement();
        ResultSet result = st.executeQuery(getReadByIDStatementString(key));
        if (result.next()) {
            object = getInstanceFromResultSet(result);
        }
        return object;
    }
References datastorage.DAOimp< T >.conn, datastorage.DAOimp< T >.getInstanceFromResultSet(), and datastorage.DAOimp< T >.getReadByIDStatementString().
Referenced by controller.TreatmentController.initializeController().
readAll()
List< T > datastorage.DAOimp< T >.readAll () throws SQLException
calls getReadAllStatementString method and makes a new list of objects out of the result
Returns
list of objects
Exceptions
SQLException
Implements datastorage.DAO< T >.
Definition at line 55 of file DAOimp.java.
{
        ArrayList<T> list = new ArrayList<T>();
        T object = null;
        Statement st = conn.createStatement();
        ResultSet result = st.executeQuery(getReadAllStatementString());
        list = getListFromResultSet(result);
        return list;
    }
References datastorage.DAOimp< T >.conn, datastorage.DAOimp< T >.getListFromResultSet(), and datastorage.DAOimp< T >.getReadAllStatementString().
Referenced by controller.NewTreatmentController.createComboBoxDataCaregiver(), and controller.AllTreatmentController.handleComboBox().
readAllUnblocked()
List< T > datastorage.DAOimp< T >.readAllUnblocked () throws SQLException
calls getReadAllUnblockedStatementString method and makes a new list of objects out of the result
Returns
list of objects
Exceptions
SQLException
Implements datastorage.DAO< T >.
Definition at line 70 of file DAOimp.java.
{
        ArrayList<T> list = new ArrayList<T>();
        T object = null;
        Statement st = conn.createStatement();
        ResultSet result = st.executeQuery(getReadAllUnblockedStatementString());
        list = getListFromResultSet(result);
        return list;
    }
References datastorage.DAOimp< T >.conn, datastorage.DAOimp< T >.getListFromResultSet(), and datastorage.DAOimp< T >.getReadAllUnblockedStatementString().
Referenced by controller.AllTreatmentController.createComboBoxDataPatient(), controller.AllCaregiverController.readAllAndShowInTableView(), controller.AllPatientController.readAllAndShowInTableView(), and controller.AllTreatmentController.readAllAndShowInTableView().
update()
void datastorage.DAOimp< T >.update (T t) throws SQLException
calls getUpdateStatementString method, with object
Parameters
t Object which gets updated
Exceptions
SQLException
Implements datastorage.DAO< T >.
Definition at line 85 of file DAOimp.java.
{
        Statement st = conn.createStatement();
        st.executeUpdate(getUpdateStatementString(t));
    }
References datastorage.DAOimp< T >.conn, and datastorage.DAOimp< T >.getUpdateStatementString().
Referenced by controller.TreatmentController.doUpdate(), controller.AllCaregiverController.doUpdate(), controller.AllPatientController.doUpdate(), controller.AllCaregiverController.handleBlockRow(), controller.AllPatientController.handleBlockRow(), and controller.AllTreatmentController.handleBlockRow().
Member Data Documentation
conn
Connection datastorage.DAOimp< T >.conn protected
Definition at line 11 of file DAOimp.java.
Referenced by datastorage.DAOimp< T >.create(), datastorage.DAOimp< T >.DAOimp(), datastorage.DAOimp< T >.deleteById(), datastorage.DAOimp< T >.getConn(), datastorage.DAOimp< T >.read(), datastorage.DAOimp< T >.readAll(), datastorage.DAOimp< T >.readAllUnblocked(), and datastorage.DAOimp< T >.update().
The documentation for this class was generated from the following file:
src/main/java/datastorage/DAOimp.java