Nursing home student: controller.AllPatientController Class Reference
controller.AllPatientController Class Reference
The AllPatientController contains the entire logic of the patient view.
Public Member Functions
void initialize ()
Initializes the corresponding fields.
void handleOnEditFirstname (TableColumn.CellEditEvent< Patient, String > event)
handles new firstname value
void handleOnEditSurname (TableColumn.CellEditEvent< Patient, String > event)
handles new surname value
void handleOnEditDateOfBirth (TableColumn.CellEditEvent< Patient, String > event)
handles new birthdate value
void handleOnEditCareLevel (TableColumn.CellEditEvent< Patient, String > event)
handles new carelevel value
void handleOnEditRoomnumber (TableColumn.CellEditEvent< Patient, String > event)
handles new roomnumber value
void handleDeleteRow ()
handles a delete-click-event.
void handleBlockRow ()
handles a block-click-event.
void handleAdd ()
handles a add-click-event.
Package Attributes
Button btnDelete
Button btnAdd
TextField txtSurname
TextField txtFirstname
TextField txtBirthday
TextField txtCarelevel
TextField txtRoom
Private Member Functions
void doUpdate (TableColumn.CellEditEvent< Patient, String > t)
updates a patient by calling the update-Method in the PatientDAO
void readAllAndShowInTableView ()
calls readAll in PatientDAO and shows patients in the table
void clearTextfields ()
removes content from all textfields
Private Attributes
TableView< Patient > tableView
TableColumn< Patient, Integer > colID
TableColumn< Patient, String > colFirstName
TableColumn< Patient, String > colSurname
TableColumn< Patient, String > colDateOfBirth
TableColumn< Patient, String > colCareLevel
TableColumn< Patient, String > colRoom
ObservableList< Patient > tableviewContent = FXCollections.observableArrayList()
PatientDAO dao
Detailed Description
The AllPatientController contains the entire logic of the patient view.
It determines which data is displayed and how to react to events.
Member Function Documentation
clearTextfields()
void controller.AllPatientController.clearTextfields () private
removes content from all textfields
{
        this.txtFirstname.clear();
        this.txtSurname.clear();
        this.txtBirthday.clear();
        this.txtCarelevel.clear();
        this.txtRoom.clear();
    }
Referenced by controller.AllPatientController.handleAdd().
doUpdate()
void controller.AllPatientController.doUpdate (TableColumn.CellEditEvent< Patient, String > t) private
updates a patient by calling the update-Method in the PatientDAO
Parameters
t row to be updated by the user (includes the patient)
{
        try {
            dao.update(t.getRowValue());
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References controller.AllPatientController.dao, and datastorage.DAOimp< T >.update().
Referenced by controller.AllPatientController.handleOnEditCareLevel(), controller.AllPatientController.handleOnEditDateOfBirth(), controller.AllPatientController.handleOnEditFirstname(), controller.AllPatientController.handleOnEditRoomnumber(), and controller.AllPatientController.handleOnEditSurname().
handleAdd()
void controller.AllPatientController.handleAdd ()
handles a add-click-event.
Creates a patient and calls the create method in the PatientDAO
{
        String surname = this.txtSurname.getText();
        String firstname = this.txtFirstname.getText();
        String birthday = this.txtBirthday.getText();
        LocalDate date = DateConverter.convertStringToLocalDate(birthday);
        String carelevel = this.txtCarelevel.getText();
        String room = this.txtRoom.getText();
        if(surname.equals("") || firstname.equals("") || birthday.equals("") || carelevel.equals("") || room.equals("")) {
            return;
        }
        try {
            Patient p = new Patient(firstname, surname, date, carelevel, room, true);
            dao.create(p);
        } catch (SQLException e) {
            e.printStackTrace();
        }
        readAllAndShowInTableView();
        clearTextfields();
    }
References controller.AllPatientController.clearTextfields(), utils.DateConverter.convertStringToLocalDate(), datastorage.DAOimp< T >.create(), controller.AllPatientController.dao, and controller.AllPatientController.readAllAndShowInTableView().
handleBlockRow()
void controller.AllPatientController.handleBlockRow ()
handles a block-click-event.
Changes the shown variable of the patient in the database to indicate if this patient should be shown
{
        TreatmentDAO tDao = DAOFactory.getDAOFactory().createTreatmentDAO();
        Patient selectedItem = this.tableView.getSelectionModel().getSelectedItem();
        try {
            List<Treatment> treatment = tDao.readTreatmentsByPid(selectedItem.getPid());
            selectedItem.setShown(false);
            dao.update(selectedItem);
            for (Treatment ActiveTreatment : treatment ) {
                ActiveTreatment.setShown(false);
                tDao.update(ActiveTreatment);
            }
            this.tableView.getItems().remove(selectedItem);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.DAOFactory.createTreatmentDAO(), controller.AllPatientController.dao, datastorage.DAOFactory.getDAOFactory(), model.Patient.getPid(), datastorage.TreatmentDAO.readTreatmentsByPid(), model.Patient.setShown(), and datastorage.DAOimp< T >.update().
handleDeleteRow()
void controller.AllPatientController.handleDeleteRow ()
handles a delete-click-event.
Calls the delete methods in the PatientDAO and TreatmentDAO
{
        TreatmentDAO tDao = DAOFactory.getDAOFactory().createTreatmentDAO();
        Patient selectedItem = this.tableView.getSelectionModel().getSelectedItem();
        try {
            tDao.deleteByPid(selectedItem.getPid());
            dao.deleteById(selectedItem.getPid());
            this.tableView.getItems().remove(selectedItem);
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.DAOFactory.createTreatmentDAO(), controller.AllPatientController.dao, datastorage.DAOimp< T >.deleteById(), datastorage.TreatmentDAO.deleteByPid(), datastorage.DAOFactory.getDAOFactory(), and model.Patient.getPid().
handleOnEditCareLevel()
void controller.AllPatientController.handleOnEditCareLevel (TableColumn.CellEditEvent< Patient, String > event)
handles new carelevel value
Parameters
event event including the value that a user entered into the cell
{
        event.getRowValue().setCareLevel(event.getNewValue());
        doUpdate(event);
    }
References controller.AllPatientController.doUpdate().
handleOnEditDateOfBirth()
void controller.AllPatientController.handleOnEditDateOfBirth (TableColumn.CellEditEvent< Patient, String > event)
handles new birthdate value
Parameters
event event including the value that a user entered into the cell
{
        event.getRowValue().setDateOfBirth(event.getNewValue());
        doUpdate(event);
    }
References controller.AllPatientController.doUpdate().
handleOnEditFirstname()
void controller.AllPatientController.handleOnEditFirstname (TableColumn.CellEditEvent< Patient, String > event)
handles new firstname value
Parameters
event event including the value that a user entered into the cell
{
        event.getRowValue().setFirstName(event.getNewValue());
        doUpdate(event);
    }
References controller.AllPatientController.doUpdate().
handleOnEditRoomnumber()
void controller.AllPatientController.handleOnEditRoomnumber (TableColumn.CellEditEvent< Patient, String > event)
handles new roomnumber value
Parameters
event event including the value that a user entered into the cell
{
        event.getRowValue().setRoomnumber(event.getNewValue());
        doUpdate(event);
    }
References controller.AllPatientController.doUpdate().
handleOnEditSurname()
void controller.AllPatientController.handleOnEditSurname (TableColumn.CellEditEvent< Patient, String > event)
handles new surname value
Parameters
event event including the value that a user entered into the cell
{
        event.getRowValue().setSurname(event.getNewValue());
        doUpdate(event);
    }
References controller.AllPatientController.doUpdate().
initialize()
void controller.AllPatientController.initialize ()
Initializes the corresponding fields.
Is called as soon as the corresponding FXML file is to be displayed.
{
        readAllAndShowInTableView();
        this.colID.setCellValueFactory(new PropertyValueFactory<Patient, Integer>("pid"));
        //CellValuefactory zum Anzeigen der Daten in der TableView
        this.colFirstName.setCellValueFactory(new PropertyValueFactory<Patient, String>("firstName"));
        //CellFactory zum Schreiben innerhalb der Tabelle
        this.colFirstName.setCellFactory(TextFieldTableCell.forTableColumn());
        this.colSurname.setCellValueFactory(new PropertyValueFactory<Patient, String>("surname"));
        this.colSurname.setCellFactory(TextFieldTableCell.forTableColumn());
        this.colDateOfBirth.setCellValueFactory(new PropertyValueFactory<Patient, String>("dateOfBirth"));
        this.colDateOfBirth.setCellFactory(TextFieldTableCell.forTableColumn());
        this.colCareLevel.setCellValueFactory(new PropertyValueFactory<Patient, String>("careLevel"));
        this.colCareLevel.setCellFactory(TextFieldTableCell.forTableColumn());
        this.colRoom.setCellValueFactory(new PropertyValueFactory<Patient, String>("roomnumber"));
        this.colRoom.setCellFactory(TextFieldTableCell.forTableColumn());
        //Anzeigen der Daten
        this.tableView.setItems(this.tableviewContent);
        try {
            Statement statement = dao.getConn().createStatement();
            statement.executeQuery("DELETE FROM patient WHERE show = FALSE AND blockeddate <= DATEADD('YEAR', -10, CURRENT_DATE);");
        } catch (SQLException e) {
            throw new RuntimeException(e);
        }
    }
References controller.AllPatientController.dao, datastorage.DAOimp< T >.getConn(), and controller.AllPatientController.readAllAndShowInTableView().
readAllAndShowInTableView()
void controller.AllPatientController.readAllAndShowInTableView () private
calls readAll in PatientDAO and shows patients in the table
{
        this.tableviewContent.clear();
        this.dao = DAOFactory.getDAOFactory().createPatientDAO();
        List<Patient> allPatients;
        try {
            allPatients = dao.readAllUnblocked();
            for (Patient p : allPatients) {
                this.tableviewContent.add(p);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }
References datastorage.DAOFactory.createPatientDAO(), controller.AllPatientController.dao, datastorage.DAOFactory.getDAOFactory(), and datastorage.DAOimp< T >.readAllUnblocked().
Referenced by controller.AllPatientController.handleAdd(), and controller.AllPatientController.initialize().
Member Data Documentation
btnAdd
Button controller.AllPatientController.btnAdd package
btnDelete
Button controller.AllPatientController.btnDelete package
colCareLevel
TableColumn<Patient, String> controller.AllPatientController.colCareLevel private
colDateOfBirth
TableColumn<Patient, String> controller.AllPatientController.colDateOfBirth private
colFirstName
TableColumn<Patient, String> controller.AllPatientController.colFirstName private
colID
TableColumn<Patient, Integer> controller.AllPatientController.colID private
colRoom
TableColumn<Patient, String> controller.AllPatientController.colRoom private
colSurname
TableColumn<Patient, String> controller.AllPatientController.colSurname private
dao
PatientDAO controller.AllPatientController.dao private
Referenced by controller.AllPatientController.doUpdate(), controller.AllPatientController.handleAdd(), controller.AllPatientController.handleBlockRow(), controller.AllPatientController.handleDeleteRow(), controller.AllPatientController.initialize(), and controller.AllPatientController.readAllAndShowInTableView().
tableView
TableView<Patient> controller.AllPatientController.tableView private
tableviewContent
ObservableList<Patient> controller.AllPatientController.tableviewContent = FXCollections.observableArrayList() private
txtBirthday
TextField controller.AllPatientController.txtBirthday package
txtCarelevel
TextField controller.AllPatientController.txtCarelevel package
txtFirstname
TextField controller.AllPatientController.txtFirstname package
txtRoom
TextField controller.AllPatientController.txtRoom package
txtSurname
TextField controller.AllPatientController.txtSurname package
The documentation for this class was generated from the following file:
src/main/java/controller/AllPatientController.java