Nursing home student: datastorage.CaregiverDAO Class Reference
datastorage.CaregiverDAO Class Reference
Implements the Interface DAOImp.
Public Member Functions
CaregiverDAO (Connection conn)
constructs Object.
Public Member Functions inherited from datastorage.DAOimp< Caregiver >
DAOimp (Connection conn)
sets Connection
void create (T t) throws SQLException
creates a new Statement of the given Object
T read (long key) throws SQLException
calls getReadByIDStatementString method and makes a new object out of the result
List< T > readAll () throws SQLException
calls getReadAllStatementString method and makes a new list of objects out of the result
List< T > readAllUnblocked () throws SQLException
calls getReadAllUnblockedStatementString method and makes a new list of objects out of the result
void update (T t) throws SQLException
calls getUpdateStatementString method, with object
void deleteById (long key) throws SQLException
calls getDeleteStatementString method, with key
Connection getConn ()
Protected Member Functions
String getCreateStatementString (Caregiver caregiver)
generates a INSERT INTO-Statement for a given caregiver
String getReadByIDStatementString (long key)
generates a select-Statement for a given key
Caregiver getInstanceFromResultSet (ResultSet result) throws SQLException
maps a ResultSet to a Caregiver
String getReadAllStatementString ()
generates a SELECT-Statement for all caregivers.
String getReadAllUnblockedStatementString ()
generates a SELECT-Statement for all caregivers, where the show variable is true.
ArrayList< Caregiver > getListFromResultSet (ResultSet result) throws SQLException
maps a ResultSet to a Caregiver-List
String getUpdateStatementString (Caregiver caregiver)
generates a UPDATE-Statement for a given caregiver
String getDeleteStatementString (long key)
generates a delete-Statement for a given key
Protected Member Functions inherited from datastorage.DAOimp< Caregiver >
abstract String getCreateStatementString (T t)
abstract String getReadByIDStatementString (long key)
abstract T getInstanceFromResultSet (ResultSet set) throws SQLException
abstract String getReadAllStatementString ()
abstract String getReadAllUnblockedStatementString ()
abstract ArrayList< T > getListFromResultSet (ResultSet set) throws SQLException
abstract String getUpdateStatementString (T t)
abstract String getDeleteStatementString (long key)
Additional Inherited Members
Protected Attributes inherited from datastorage.DAOimp< Caregiver >
Connection conn
Detailed Description
Implements the Interface DAOImp.
Overrides methods to generate specific caregiver-SQL-queries.
Constructor & Destructor Documentation
CaregiverDAO()
datastorage.CaregiverDAO.CaregiverDAO (Connection conn)
constructs Object.
Calls the Constructor from DAOImp to store the connection.
Parameters
conn
{
        super(conn);
    }
References datastorage.DAOimp< Caregiver >.conn.
Member Function Documentation
getCreateStatementString()
String datastorage.CaregiverDAO.getCreateStatementString (Caregiver caregiver) protected
generates a INSERT INTO-Statement for a given caregiver
Parameters
caregiver for which a specific INSERT INTO is to be created
Returns
String with the generated SQL.
{
        return String.format("INSERT INTO caregiver (firstname, surname, telephone, show, blockeddate) VALUES ('%s', '%s', '%s', '%s', %s)",
                caregiver.getFirstName(), caregiver.getSurname(), caregiver.getTelephone(), true, null);
    }
References model.Person.getFirstName(), model.Person.getSurname(), and model.Caregiver.getTelephone().
getDeleteStatementString()
String datastorage.CaregiverDAO.getDeleteStatementString (long key) protected
generates a delete-Statement for a given key
Parameters
key for which a specific DELETE is to be created
Returns
String with the generated SQL.
{
        return String.format("Delete FROM caregiver WHERE id=%d", key);
    }
getInstanceFromResultSet()
Caregiver datastorage.CaregiverDAO.getInstanceFromResultSet (ResultSet result) throws SQLException protected
maps a ResultSet to a Caregiver
Parameters
result ResultSet with a single row. Columns will be mapped to a caregiver-object.
Returns
caregiver with the data from the resultSet.
{
        Caregiver caregiver = null;
        caregiver = new Caregiver(result.getInt(1), result.getString(2),
                result.getString(3), result.getString(4), result.getBoolean(5));
        return caregiver;
    }
getListFromResultSet()
ArrayList< Caregiver > datastorage.CaregiverDAO.getListFromResultSet (ResultSet result) throws SQLException protected
maps a ResultSet to a Caregiver-List
Parameters
result ResultSet with a multiple rows. Data will be mapped to caregiver-object.
Returns
ArrayList with caregivers from the resultSet.
{
        ArrayList<Caregiver> list = new ArrayList<Caregiver>();
        Caregiver caregiver = null;
        while (result.next()) {
            caregiver = new Caregiver(result.getInt(1), result.getString(2),
                    result.getString(3), result.getString(4), result.getBoolean(5));
            list.add(caregiver);
        }
        return list;
    }
getReadAllStatementString()
String datastorage.CaregiverDAO.getReadAllStatementString () protected
generates a SELECT-Statement for all caregivers.
Returns
String with the generated SQL.
{
        return "SELECT * FROM caregiver";
    }
getReadAllUnblockedStatementString()
String datastorage.CaregiverDAO.getReadAllUnblockedStatementString () protected
generates a SELECT-Statement for all caregivers, where the show variable is true.
Returns
String with the generated SQL.
{
        return "SELECT * FROM caregiver WHERE show = true";
    }
getReadByIDStatementString()
String datastorage.CaregiverDAO.getReadByIDStatementString (long key) protected
generates a select-Statement for a given key
Parameters
key for which a specific SELECT is to be created
Returns
String with the generated SQL.
{
        return String.format("SELECT * FROM caregiver WHERE id = %d AND show = true", key);
    }
getUpdateStatementString()
String datastorage.CaregiverDAO.getUpdateStatementString (Caregiver caregiver) protected
generates a UPDATE-Statement for a given caregiver
Parameters
caregiver for which a specific update is to be created
Returns
String with the generated SQL.
{
        return String.format("UPDATE caregiver SET firstname = '%s', surname = '%s', telephone = '%s', SHOW = '%s', blockeddate = %s  WHERE id = %d",
                caregiver.getFirstName(), caregiver.getSurname(), caregiver.getTelephone(), caregiver.isShown(), caregiver.isShown() ? "NULL" : "'" + new SimpleDateFormat("yyyy-MM-dd").format(Calendar.getInstance().getTime()) + "'",caregiver.getId());
    }
References model.Person.getFirstName(), model.Caregiver.getId(), model.Person.getSurname(), model.Caregiver.getTelephone(), and model.Caregiver.isShown().
The documentation for this class was generated from the following file:
src/main/java/datastorage/CaregiverDAO.java